/**
 * @fileoverview gRPC-Web generated client stub for cs3.admin.user.v1beta1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v0.0.0
// source: cs3/admin/user/v1beta1/user_api.proto


/* eslint-disable */
// @ts-nocheck


goog.provide('proto.cs3.admin.user.v1beta1.UserAPIClient');
goog.provide('proto.cs3.admin.user.v1beta1.UserAPIPromiseClient');

goog.require('grpc.web.MethodDescriptor');
goog.require('grpc.web.MethodType');
goog.require('grpc.web.GrpcWebClientBase');
goog.require('grpc.web.AbstractClientBase');
goog.require('grpc.web.ClientReadableStream');
goog.require('grpc.web.RpcError');
goog.require('proto.cs3.admin.user.v1beta1.CreateUserRequest');
goog.require('proto.cs3.admin.user.v1beta1.CreateUserResponse');
goog.require('proto.cs3.admin.user.v1beta1.DeleteUserRequest');
goog.require('proto.cs3.admin.user.v1beta1.DeleteUserResponse');

goog.requireType('grpc.web.ClientOptions');



goog.scope(function() {

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.cs3.admin.user.v1beta1.UserAPIClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.cs3.admin.user.v1beta1.UserAPIPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.admin.user.v1beta1.CreateUserRequest,
 *   !proto.cs3.admin.user.v1beta1.CreateUserResponse>}
 */
const methodDescriptor_UserAPI_CreateUser = new grpc.web.MethodDescriptor(
  '/cs3.admin.user.v1beta1.UserAPI/CreateUser',
  grpc.web.MethodType.UNARY,
  proto.cs3.admin.user.v1beta1.CreateUserRequest,
  proto.cs3.admin.user.v1beta1.CreateUserResponse,
  /**
   * @param {!proto.cs3.admin.user.v1beta1.CreateUserRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.admin.user.v1beta1.CreateUserResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.admin.user.v1beta1.CreateUserRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cs3.admin.user.v1beta1.CreateUserResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.admin.user.v1beta1.CreateUserResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cs3.admin.user.v1beta1.UserAPIClient.prototype.createUser =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cs3.admin.user.v1beta1.UserAPI/CreateUser',
      request,
      metadata || {},
      methodDescriptor_UserAPI_CreateUser,
      callback);
};


/**
 * @param {!proto.cs3.admin.user.v1beta1.CreateUserRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cs3.admin.user.v1beta1.CreateUserResponse>}
 *     Promise that resolves to the response
 */
proto.cs3.admin.user.v1beta1.UserAPIPromiseClient.prototype.createUser =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cs3.admin.user.v1beta1.UserAPI/CreateUser',
      request,
      metadata || {},
      methodDescriptor_UserAPI_CreateUser);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.admin.user.v1beta1.DeleteUserRequest,
 *   !proto.cs3.admin.user.v1beta1.DeleteUserResponse>}
 */
const methodDescriptor_UserAPI_DeleteUser = new grpc.web.MethodDescriptor(
  '/cs3.admin.user.v1beta1.UserAPI/DeleteUser',
  grpc.web.MethodType.UNARY,
  proto.cs3.admin.user.v1beta1.DeleteUserRequest,
  proto.cs3.admin.user.v1beta1.DeleteUserResponse,
  /**
   * @param {!proto.cs3.admin.user.v1beta1.DeleteUserRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.admin.user.v1beta1.DeleteUserResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.admin.user.v1beta1.DeleteUserRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cs3.admin.user.v1beta1.DeleteUserResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.admin.user.v1beta1.DeleteUserResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cs3.admin.user.v1beta1.UserAPIClient.prototype.deleteUser =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cs3.admin.user.v1beta1.UserAPI/DeleteUser',
      request,
      metadata || {},
      methodDescriptor_UserAPI_DeleteUser,
      callback);
};


/**
 * @param {!proto.cs3.admin.user.v1beta1.DeleteUserRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cs3.admin.user.v1beta1.DeleteUserResponse>}
 *     Promise that resolves to the response
 */
proto.cs3.admin.user.v1beta1.UserAPIPromiseClient.prototype.deleteUser =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cs3.admin.user.v1beta1.UserAPI/DeleteUser',
      request,
      metadata || {},
      methodDescriptor_UserAPI_DeleteUser);
};


}); // goog.scope

