/**
 * @fileoverview gRPC-Web generated client stub for cs3.app.provider.v1beta1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v0.0.0
// source: cs3/app/provider/v1beta1/provider_api.proto


/* eslint-disable */
// @ts-nocheck


goog.provide('proto.cs3.app.provider.v1beta1.ProviderAPIClient');
goog.provide('proto.cs3.app.provider.v1beta1.ProviderAPIPromiseClient');

goog.require('grpc.web.MethodDescriptor');
goog.require('grpc.web.MethodType');
goog.require('grpc.web.GrpcWebClientBase');
goog.require('grpc.web.AbstractClientBase');
goog.require('grpc.web.ClientReadableStream');
goog.require('grpc.web.RpcError');
goog.require('proto.cs3.app.provider.v1beta1.OpenInAppRequest');
goog.require('proto.cs3.app.provider.v1beta1.OpenInAppResponse');

goog.requireType('grpc.web.ClientOptions');



goog.scope(function() {

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.cs3.app.provider.v1beta1.ProviderAPIClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.cs3.app.provider.v1beta1.ProviderAPIPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.app.provider.v1beta1.OpenInAppRequest,
 *   !proto.cs3.app.provider.v1beta1.OpenInAppResponse>}
 */
const methodDescriptor_ProviderAPI_OpenInApp = new grpc.web.MethodDescriptor(
  '/cs3.app.provider.v1beta1.ProviderAPI/OpenInApp',
  grpc.web.MethodType.UNARY,
  proto.cs3.app.provider.v1beta1.OpenInAppRequest,
  proto.cs3.app.provider.v1beta1.OpenInAppResponse,
  /**
   * @param {!proto.cs3.app.provider.v1beta1.OpenInAppRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.app.provider.v1beta1.OpenInAppResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.app.provider.v1beta1.OpenInAppRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cs3.app.provider.v1beta1.OpenInAppResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.app.provider.v1beta1.OpenInAppResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cs3.app.provider.v1beta1.ProviderAPIClient.prototype.openInApp =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cs3.app.provider.v1beta1.ProviderAPI/OpenInApp',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_OpenInApp,
      callback);
};


/**
 * @param {!proto.cs3.app.provider.v1beta1.OpenInAppRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cs3.app.provider.v1beta1.OpenInAppResponse>}
 *     Promise that resolves to the response
 */
proto.cs3.app.provider.v1beta1.ProviderAPIPromiseClient.prototype.openInApp =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cs3.app.provider.v1beta1.ProviderAPI/OpenInApp',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_OpenInApp);
};


}); // goog.scope

