// source: cs3/gateway/v1beta1/resources.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.cs3.gateway.v1beta1.FileUploadProtocol');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.cs3.storage.provider.v1beta1.ResourceChecksumPriority');
goog.require('proto.cs3.types.v1beta1.Opaque');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cs3.gateway.v1beta1.FileUploadProtocol = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.cs3.gateway.v1beta1.FileUploadProtocol.repeatedFields_, null);
};
goog.inherits(proto.cs3.gateway.v1beta1.FileUploadProtocol, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cs3.gateway.v1beta1.FileUploadProtocol.displayName = 'proto.cs3.gateway.v1beta1.FileUploadProtocol';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.cs3.gateway.v1beta1.FileUploadProtocol.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cs3.gateway.v1beta1.FileUploadProtocol.prototype.toObject = function(opt_includeInstance) {
  return proto.cs3.gateway.v1beta1.FileUploadProtocol.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cs3.gateway.v1beta1.FileUploadProtocol} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.gateway.v1beta1.FileUploadProtocol.toObject = function(includeInstance, msg) {
  var f, obj = {
    opaque: (f = msg.getOpaque()) && proto.cs3.types.v1beta1.Opaque.toObject(includeInstance, f),
    protocol: jspb.Message.getFieldWithDefault(msg, 2, ""),
    uploadEndpoint: jspb.Message.getFieldWithDefault(msg, 3, ""),
    availableChecksumsList: jspb.Message.toObjectList(msg.getAvailableChecksumsList(),
    proto.cs3.storage.provider.v1beta1.ResourceChecksumPriority.toObject, includeInstance),
    token: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cs3.gateway.v1beta1.FileUploadProtocol}
 */
proto.cs3.gateway.v1beta1.FileUploadProtocol.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cs3.gateway.v1beta1.FileUploadProtocol;
  return proto.cs3.gateway.v1beta1.FileUploadProtocol.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cs3.gateway.v1beta1.FileUploadProtocol} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cs3.gateway.v1beta1.FileUploadProtocol}
 */
proto.cs3.gateway.v1beta1.FileUploadProtocol.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.cs3.types.v1beta1.Opaque;
      reader.readMessage(value,proto.cs3.types.v1beta1.Opaque.deserializeBinaryFromReader);
      msg.setOpaque(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setProtocol(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setUploadEndpoint(value);
      break;
    case 4:
      var value = new proto.cs3.storage.provider.v1beta1.ResourceChecksumPriority;
      reader.readMessage(value,proto.cs3.storage.provider.v1beta1.ResourceChecksumPriority.deserializeBinaryFromReader);
      msg.addAvailableChecksums(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setToken(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cs3.gateway.v1beta1.FileUploadProtocol.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cs3.gateway.v1beta1.FileUploadProtocol.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cs3.gateway.v1beta1.FileUploadProtocol} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.gateway.v1beta1.FileUploadProtocol.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOpaque();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.cs3.types.v1beta1.Opaque.serializeBinaryToWriter
    );
  }
  f = message.getProtocol();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getUploadEndpoint();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getAvailableChecksumsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.cs3.storage.provider.v1beta1.ResourceChecksumPriority.serializeBinaryToWriter
    );
  }
  f = message.getToken();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional cs3.types.v1beta1.Opaque opaque = 1;
 * @return {?proto.cs3.types.v1beta1.Opaque}
 */
proto.cs3.gateway.v1beta1.FileUploadProtocol.prototype.getOpaque = function() {
  return /** @type{?proto.cs3.types.v1beta1.Opaque} */ (
    jspb.Message.getWrapperField(this, proto.cs3.types.v1beta1.Opaque, 1));
};


/**
 * @param {?proto.cs3.types.v1beta1.Opaque|undefined} value
 * @return {!proto.cs3.gateway.v1beta1.FileUploadProtocol} returns this
*/
proto.cs3.gateway.v1beta1.FileUploadProtocol.prototype.setOpaque = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.gateway.v1beta1.FileUploadProtocol} returns this
 */
proto.cs3.gateway.v1beta1.FileUploadProtocol.prototype.clearOpaque = function() {
  return this.setOpaque(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.gateway.v1beta1.FileUploadProtocol.prototype.hasOpaque = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string protocol = 2;
 * @return {string}
 */
proto.cs3.gateway.v1beta1.FileUploadProtocol.prototype.getProtocol = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.cs3.gateway.v1beta1.FileUploadProtocol} returns this
 */
proto.cs3.gateway.v1beta1.FileUploadProtocol.prototype.setProtocol = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string upload_endpoint = 3;
 * @return {string}
 */
proto.cs3.gateway.v1beta1.FileUploadProtocol.prototype.getUploadEndpoint = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.cs3.gateway.v1beta1.FileUploadProtocol} returns this
 */
proto.cs3.gateway.v1beta1.FileUploadProtocol.prototype.setUploadEndpoint = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * repeated cs3.storage.provider.v1beta1.ResourceChecksumPriority available_checksums = 4;
 * @return {!Array<!proto.cs3.storage.provider.v1beta1.ResourceChecksumPriority>}
 */
proto.cs3.gateway.v1beta1.FileUploadProtocol.prototype.getAvailableChecksumsList = function() {
  return /** @type{!Array<!proto.cs3.storage.provider.v1beta1.ResourceChecksumPriority>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.cs3.storage.provider.v1beta1.ResourceChecksumPriority, 4));
};


/**
 * @param {!Array<!proto.cs3.storage.provider.v1beta1.ResourceChecksumPriority>} value
 * @return {!proto.cs3.gateway.v1beta1.FileUploadProtocol} returns this
*/
proto.cs3.gateway.v1beta1.FileUploadProtocol.prototype.setAvailableChecksumsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.cs3.storage.provider.v1beta1.ResourceChecksumPriority=} opt_value
 * @param {number=} opt_index
 * @return {!proto.cs3.storage.provider.v1beta1.ResourceChecksumPriority}
 */
proto.cs3.gateway.v1beta1.FileUploadProtocol.prototype.addAvailableChecksums = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.cs3.storage.provider.v1beta1.ResourceChecksumPriority, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.cs3.gateway.v1beta1.FileUploadProtocol} returns this
 */
proto.cs3.gateway.v1beta1.FileUploadProtocol.prototype.clearAvailableChecksumsList = function() {
  return this.setAvailableChecksumsList([]);
};


/**
 * optional string token = 5;
 * @return {string}
 */
proto.cs3.gateway.v1beta1.FileUploadProtocol.prototype.getToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.cs3.gateway.v1beta1.FileUploadProtocol} returns this
 */
proto.cs3.gateway.v1beta1.FileUploadProtocol.prototype.setToken = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


