// source: cs3/sharing/ocm/v1beta1/ocm_api.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest');
goog.provide('proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter');
goog.provide('proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter.TermCase');
goog.provide('proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter.Type');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.cs3.identity.user.v1beta1.UserId');
goog.require('proto.cs3.types.v1beta1.Opaque');

goog.forwardDeclare('proto.cs3.sharing.ocm.v1beta1.SharedResourceType');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.repeatedFields_, null);
};
goog.inherits(proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.displayName = 'proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter.oneofGroups_);
};
goog.inherits(proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter.displayName = 'proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    opaque: (f = msg.getOpaque()) && proto.cs3.types.v1beta1.Opaque.toObject(includeInstance, f),
    pageSize: jspb.Message.getFieldWithDefault(msg, 2, 0),
    pageToken: jspb.Message.getFieldWithDefault(msg, 3, ""),
    filtersList: jspb.Message.toObjectList(msg.getFiltersList(),
    proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest}
 */
proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest;
  return proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest}
 */
proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.cs3.types.v1beta1.Opaque;
      reader.readMessage(value,proto.cs3.types.v1beta1.Opaque.deserializeBinaryFromReader);
      msg.setOpaque(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPageSize(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setPageToken(value);
      break;
    case 4:
      var value = new proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter;
      reader.readMessage(value,proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter.deserializeBinaryFromReader);
      msg.addFilters(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOpaque();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.cs3.types.v1beta1.Opaque.serializeBinaryToWriter
    );
  }
  f = message.getPageSize();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getPageToken();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getFiltersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter.serializeBinaryToWriter
    );
  }
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter.oneofGroups_ = [[2,3,4]];

/**
 * @enum {number}
 */
proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter.TermCase = {
  TERM_NOT_SET: 0,
  OWNER: 2,
  CREATOR: 3,
  SHARED_RESOURCE_TYPE: 4
};

/**
 * @return {proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter.TermCase}
 */
proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter.prototype.getTermCase = function() {
  return /** @type {proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter.TermCase} */(jspb.Message.computeOneofCase(this, proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter.prototype.toObject = function(opt_includeInstance) {
  return proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, 0),
    owner: (f = msg.getOwner()) && proto.cs3.identity.user.v1beta1.UserId.toObject(includeInstance, f),
    creator: (f = msg.getCreator()) && proto.cs3.identity.user.v1beta1.UserId.toObject(includeInstance, f),
    sharedResourceType: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter}
 */
proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter;
  return proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter}
 */
proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter.Type} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 2:
      var value = new proto.cs3.identity.user.v1beta1.UserId;
      reader.readMessage(value,proto.cs3.identity.user.v1beta1.UserId.deserializeBinaryFromReader);
      msg.setOwner(value);
      break;
    case 3:
      var value = new proto.cs3.identity.user.v1beta1.UserId;
      reader.readMessage(value,proto.cs3.identity.user.v1beta1.UserId.deserializeBinaryFromReader);
      msg.setCreator(value);
      break;
    case 4:
      var value = /** @type {!proto.cs3.sharing.ocm.v1beta1.SharedResourceType} */ (reader.readEnum());
      msg.setSharedResourceType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getOwner();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.cs3.identity.user.v1beta1.UserId.serializeBinaryToWriter
    );
  }
  f = message.getCreator();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.cs3.identity.user.v1beta1.UserId.serializeBinaryToWriter
    );
  }
  f = /** @type {!proto.cs3.sharing.ocm.v1beta1.SharedResourceType} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeEnum(
      4,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter.Type = {
  TYPE_INVALID: 0,
  TYPE_OWNER: 1,
  TYPE_CREATOR: 2,
  TYPE_SHARE_TYPE: 3
};

/**
 * optional Type type = 1;
 * @return {!proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter.Type}
 */
proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter.prototype.getType = function() {
  return /** @type {!proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter.Type} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter.Type} value
 * @return {!proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter} returns this
 */
proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional cs3.identity.user.v1beta1.UserId owner = 2;
 * @return {?proto.cs3.identity.user.v1beta1.UserId}
 */
proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter.prototype.getOwner = function() {
  return /** @type{?proto.cs3.identity.user.v1beta1.UserId} */ (
    jspb.Message.getWrapperField(this, proto.cs3.identity.user.v1beta1.UserId, 2));
};


/**
 * @param {?proto.cs3.identity.user.v1beta1.UserId|undefined} value
 * @return {!proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter} returns this
*/
proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter.prototype.setOwner = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter} returns this
 */
proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter.prototype.clearOwner = function() {
  return this.setOwner(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter.prototype.hasOwner = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional cs3.identity.user.v1beta1.UserId creator = 3;
 * @return {?proto.cs3.identity.user.v1beta1.UserId}
 */
proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter.prototype.getCreator = function() {
  return /** @type{?proto.cs3.identity.user.v1beta1.UserId} */ (
    jspb.Message.getWrapperField(this, proto.cs3.identity.user.v1beta1.UserId, 3));
};


/**
 * @param {?proto.cs3.identity.user.v1beta1.UserId|undefined} value
 * @return {!proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter} returns this
*/
proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter.prototype.setCreator = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter} returns this
 */
proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter.prototype.clearCreator = function() {
  return this.setCreator(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter.prototype.hasCreator = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional SharedResourceType shared_resource_type = 4;
 * @return {!proto.cs3.sharing.ocm.v1beta1.SharedResourceType}
 */
proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter.prototype.getSharedResourceType = function() {
  return /** @type {!proto.cs3.sharing.ocm.v1beta1.SharedResourceType} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.cs3.sharing.ocm.v1beta1.SharedResourceType} value
 * @return {!proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter} returns this
 */
proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter.prototype.setSharedResourceType = function(value) {
  return jspb.Message.setOneofField(this, 4, proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter} returns this
 */
proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter.prototype.clearSharedResourceType = function() {
  return jspb.Message.setOneofField(this, 4, proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter.prototype.hasSharedResourceType = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional cs3.types.v1beta1.Opaque opaque = 1;
 * @return {?proto.cs3.types.v1beta1.Opaque}
 */
proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.prototype.getOpaque = function() {
  return /** @type{?proto.cs3.types.v1beta1.Opaque} */ (
    jspb.Message.getWrapperField(this, proto.cs3.types.v1beta1.Opaque, 1));
};


/**
 * @param {?proto.cs3.types.v1beta1.Opaque|undefined} value
 * @return {!proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest} returns this
*/
proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.prototype.setOpaque = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest} returns this
 */
proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.prototype.clearOpaque = function() {
  return this.setOpaque(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.prototype.hasOpaque = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int32 page_size = 2;
 * @return {number}
 */
proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.prototype.getPageSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest} returns this
 */
proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.prototype.setPageSize = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string page_token = 3;
 * @return {string}
 */
proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.prototype.getPageToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest} returns this
 */
proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.prototype.setPageToken = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * repeated Filter filters = 4;
 * @return {!Array<!proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter>}
 */
proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.prototype.getFiltersList = function() {
  return /** @type{!Array<!proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter, 4));
};


/**
 * @param {!Array<!proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter>} value
 * @return {!proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest} returns this
*/
proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.prototype.setFiltersList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter=} opt_value
 * @param {number=} opt_index
 * @return {!proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter}
 */
proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.prototype.addFilters = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.Filter, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest} returns this
 */
proto.cs3.sharing.ocm.v1beta1.ListReceivedOCMSharesRequest.prototype.clearFiltersList = function() {
  return this.setFiltersList([]);
};


