// source: cs3/storage/provider/v1beta1/resources.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.cs3.storage.provider.v1beta1.ResourcePermissions');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cs3.storage.provider.v1beta1.ResourcePermissions = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cs3.storage.provider.v1beta1.ResourcePermissions, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cs3.storage.provider.v1beta1.ResourcePermissions.displayName = 'proto.cs3.storage.provider.v1beta1.ResourcePermissions';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cs3.storage.provider.v1beta1.ResourcePermissions.prototype.toObject = function(opt_includeInstance) {
  return proto.cs3.storage.provider.v1beta1.ResourcePermissions.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cs3.storage.provider.v1beta1.ResourcePermissions} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.storage.provider.v1beta1.ResourcePermissions.toObject = function(includeInstance, msg) {
  var f, obj = {
    addGrant: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    createContainer: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    pb_delete: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    getPath: jspb.Message.getBooleanFieldWithDefault(msg, 5, false),
    getQuota: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
    initiateFileDownload: jspb.Message.getBooleanFieldWithDefault(msg, 7, false),
    initiateFileUpload: jspb.Message.getBooleanFieldWithDefault(msg, 8, false),
    listGrants: jspb.Message.getBooleanFieldWithDefault(msg, 9, false),
    listContainer: jspb.Message.getBooleanFieldWithDefault(msg, 10, false),
    listFileVersions: jspb.Message.getBooleanFieldWithDefault(msg, 11, false),
    listRecycle: jspb.Message.getBooleanFieldWithDefault(msg, 12, false),
    move: jspb.Message.getBooleanFieldWithDefault(msg, 13, false),
    removeGrant: jspb.Message.getBooleanFieldWithDefault(msg, 14, false),
    purgeRecycle: jspb.Message.getBooleanFieldWithDefault(msg, 15, false),
    restoreFileVersion: jspb.Message.getBooleanFieldWithDefault(msg, 16, false),
    restoreRecycleItem: jspb.Message.getBooleanFieldWithDefault(msg, 17, false),
    stat: jspb.Message.getBooleanFieldWithDefault(msg, 18, false),
    updateGrant: jspb.Message.getBooleanFieldWithDefault(msg, 19, false),
    denyGrant: jspb.Message.getBooleanFieldWithDefault(msg, 20, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cs3.storage.provider.v1beta1.ResourcePermissions}
 */
proto.cs3.storage.provider.v1beta1.ResourcePermissions.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cs3.storage.provider.v1beta1.ResourcePermissions;
  return proto.cs3.storage.provider.v1beta1.ResourcePermissions.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cs3.storage.provider.v1beta1.ResourcePermissions} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cs3.storage.provider.v1beta1.ResourcePermissions}
 */
proto.cs3.storage.provider.v1beta1.ResourcePermissions.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAddGrant(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setCreateContainer(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setDelete(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setGetPath(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setGetQuota(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setInitiateFileDownload(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setInitiateFileUpload(value);
      break;
    case 9:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setListGrants(value);
      break;
    case 10:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setListContainer(value);
      break;
    case 11:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setListFileVersions(value);
      break;
    case 12:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setListRecycle(value);
      break;
    case 13:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setMove(value);
      break;
    case 14:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRemoveGrant(value);
      break;
    case 15:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setPurgeRecycle(value);
      break;
    case 16:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRestoreFileVersion(value);
      break;
    case 17:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRestoreRecycleItem(value);
      break;
    case 18:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setStat(value);
      break;
    case 19:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setUpdateGrant(value);
      break;
    case 20:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setDenyGrant(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cs3.storage.provider.v1beta1.ResourcePermissions.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cs3.storage.provider.v1beta1.ResourcePermissions.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cs3.storage.provider.v1beta1.ResourcePermissions} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.storage.provider.v1beta1.ResourcePermissions.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAddGrant();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getCreateContainer();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getDelete();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getGetPath();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
  f = message.getGetQuota();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getInitiateFileDownload();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
  f = message.getInitiateFileUpload();
  if (f) {
    writer.writeBool(
      8,
      f
    );
  }
  f = message.getListGrants();
  if (f) {
    writer.writeBool(
      9,
      f
    );
  }
  f = message.getListContainer();
  if (f) {
    writer.writeBool(
      10,
      f
    );
  }
  f = message.getListFileVersions();
  if (f) {
    writer.writeBool(
      11,
      f
    );
  }
  f = message.getListRecycle();
  if (f) {
    writer.writeBool(
      12,
      f
    );
  }
  f = message.getMove();
  if (f) {
    writer.writeBool(
      13,
      f
    );
  }
  f = message.getRemoveGrant();
  if (f) {
    writer.writeBool(
      14,
      f
    );
  }
  f = message.getPurgeRecycle();
  if (f) {
    writer.writeBool(
      15,
      f
    );
  }
  f = message.getRestoreFileVersion();
  if (f) {
    writer.writeBool(
      16,
      f
    );
  }
  f = message.getRestoreRecycleItem();
  if (f) {
    writer.writeBool(
      17,
      f
    );
  }
  f = message.getStat();
  if (f) {
    writer.writeBool(
      18,
      f
    );
  }
  f = message.getUpdateGrant();
  if (f) {
    writer.writeBool(
      19,
      f
    );
  }
  f = message.getDenyGrant();
  if (f) {
    writer.writeBool(
      20,
      f
    );
  }
};


/**
 * optional bool add_grant = 1;
 * @return {boolean}
 */
proto.cs3.storage.provider.v1beta1.ResourcePermissions.prototype.getAddGrant = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.cs3.storage.provider.v1beta1.ResourcePermissions} returns this
 */
proto.cs3.storage.provider.v1beta1.ResourcePermissions.prototype.setAddGrant = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional bool create_container = 2;
 * @return {boolean}
 */
proto.cs3.storage.provider.v1beta1.ResourcePermissions.prototype.getCreateContainer = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.cs3.storage.provider.v1beta1.ResourcePermissions} returns this
 */
proto.cs3.storage.provider.v1beta1.ResourcePermissions.prototype.setCreateContainer = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional bool delete = 3;
 * @return {boolean}
 */
proto.cs3.storage.provider.v1beta1.ResourcePermissions.prototype.getDelete = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.cs3.storage.provider.v1beta1.ResourcePermissions} returns this
 */
proto.cs3.storage.provider.v1beta1.ResourcePermissions.prototype.setDelete = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional bool get_path = 5;
 * @return {boolean}
 */
proto.cs3.storage.provider.v1beta1.ResourcePermissions.prototype.getGetPath = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.cs3.storage.provider.v1beta1.ResourcePermissions} returns this
 */
proto.cs3.storage.provider.v1beta1.ResourcePermissions.prototype.setGetPath = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};


/**
 * optional bool get_quota = 6;
 * @return {boolean}
 */
proto.cs3.storage.provider.v1beta1.ResourcePermissions.prototype.getGetQuota = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.cs3.storage.provider.v1beta1.ResourcePermissions} returns this
 */
proto.cs3.storage.provider.v1beta1.ResourcePermissions.prototype.setGetQuota = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional bool initiate_file_download = 7;
 * @return {boolean}
 */
proto.cs3.storage.provider.v1beta1.ResourcePermissions.prototype.getInitiateFileDownload = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.cs3.storage.provider.v1beta1.ResourcePermissions} returns this
 */
proto.cs3.storage.provider.v1beta1.ResourcePermissions.prototype.setInitiateFileDownload = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};


/**
 * optional bool initiate_file_upload = 8;
 * @return {boolean}
 */
proto.cs3.storage.provider.v1beta1.ResourcePermissions.prototype.getInitiateFileUpload = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false));
};


/**
 * @param {boolean} value
 * @return {!proto.cs3.storage.provider.v1beta1.ResourcePermissions} returns this
 */
proto.cs3.storage.provider.v1beta1.ResourcePermissions.prototype.setInitiateFileUpload = function(value) {
  return jspb.Message.setProto3BooleanField(this, 8, value);
};


/**
 * optional bool list_grants = 9;
 * @return {boolean}
 */
proto.cs3.storage.provider.v1beta1.ResourcePermissions.prototype.getListGrants = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 9, false));
};


/**
 * @param {boolean} value
 * @return {!proto.cs3.storage.provider.v1beta1.ResourcePermissions} returns this
 */
proto.cs3.storage.provider.v1beta1.ResourcePermissions.prototype.setListGrants = function(value) {
  return jspb.Message.setProto3BooleanField(this, 9, value);
};


/**
 * optional bool list_container = 10;
 * @return {boolean}
 */
proto.cs3.storage.provider.v1beta1.ResourcePermissions.prototype.getListContainer = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 10, false));
};


/**
 * @param {boolean} value
 * @return {!proto.cs3.storage.provider.v1beta1.ResourcePermissions} returns this
 */
proto.cs3.storage.provider.v1beta1.ResourcePermissions.prototype.setListContainer = function(value) {
  return jspb.Message.setProto3BooleanField(this, 10, value);
};


/**
 * optional bool list_file_versions = 11;
 * @return {boolean}
 */
proto.cs3.storage.provider.v1beta1.ResourcePermissions.prototype.getListFileVersions = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 11, false));
};


/**
 * @param {boolean} value
 * @return {!proto.cs3.storage.provider.v1beta1.ResourcePermissions} returns this
 */
proto.cs3.storage.provider.v1beta1.ResourcePermissions.prototype.setListFileVersions = function(value) {
  return jspb.Message.setProto3BooleanField(this, 11, value);
};


/**
 * optional bool list_recycle = 12;
 * @return {boolean}
 */
proto.cs3.storage.provider.v1beta1.ResourcePermissions.prototype.getListRecycle = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 12, false));
};


/**
 * @param {boolean} value
 * @return {!proto.cs3.storage.provider.v1beta1.ResourcePermissions} returns this
 */
proto.cs3.storage.provider.v1beta1.ResourcePermissions.prototype.setListRecycle = function(value) {
  return jspb.Message.setProto3BooleanField(this, 12, value);
};


/**
 * optional bool move = 13;
 * @return {boolean}
 */
proto.cs3.storage.provider.v1beta1.ResourcePermissions.prototype.getMove = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 13, false));
};


/**
 * @param {boolean} value
 * @return {!proto.cs3.storage.provider.v1beta1.ResourcePermissions} returns this
 */
proto.cs3.storage.provider.v1beta1.ResourcePermissions.prototype.setMove = function(value) {
  return jspb.Message.setProto3BooleanField(this, 13, value);
};


/**
 * optional bool remove_grant = 14;
 * @return {boolean}
 */
proto.cs3.storage.provider.v1beta1.ResourcePermissions.prototype.getRemoveGrant = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 14, false));
};


/**
 * @param {boolean} value
 * @return {!proto.cs3.storage.provider.v1beta1.ResourcePermissions} returns this
 */
proto.cs3.storage.provider.v1beta1.ResourcePermissions.prototype.setRemoveGrant = function(value) {
  return jspb.Message.setProto3BooleanField(this, 14, value);
};


/**
 * optional bool purge_recycle = 15;
 * @return {boolean}
 */
proto.cs3.storage.provider.v1beta1.ResourcePermissions.prototype.getPurgeRecycle = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 15, false));
};


/**
 * @param {boolean} value
 * @return {!proto.cs3.storage.provider.v1beta1.ResourcePermissions} returns this
 */
proto.cs3.storage.provider.v1beta1.ResourcePermissions.prototype.setPurgeRecycle = function(value) {
  return jspb.Message.setProto3BooleanField(this, 15, value);
};


/**
 * optional bool restore_file_version = 16;
 * @return {boolean}
 */
proto.cs3.storage.provider.v1beta1.ResourcePermissions.prototype.getRestoreFileVersion = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 16, false));
};


/**
 * @param {boolean} value
 * @return {!proto.cs3.storage.provider.v1beta1.ResourcePermissions} returns this
 */
proto.cs3.storage.provider.v1beta1.ResourcePermissions.prototype.setRestoreFileVersion = function(value) {
  return jspb.Message.setProto3BooleanField(this, 16, value);
};


/**
 * optional bool restore_recycle_item = 17;
 * @return {boolean}
 */
proto.cs3.storage.provider.v1beta1.ResourcePermissions.prototype.getRestoreRecycleItem = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 17, false));
};


/**
 * @param {boolean} value
 * @return {!proto.cs3.storage.provider.v1beta1.ResourcePermissions} returns this
 */
proto.cs3.storage.provider.v1beta1.ResourcePermissions.prototype.setRestoreRecycleItem = function(value) {
  return jspb.Message.setProto3BooleanField(this, 17, value);
};


/**
 * optional bool stat = 18;
 * @return {boolean}
 */
proto.cs3.storage.provider.v1beta1.ResourcePermissions.prototype.getStat = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 18, false));
};


/**
 * @param {boolean} value
 * @return {!proto.cs3.storage.provider.v1beta1.ResourcePermissions} returns this
 */
proto.cs3.storage.provider.v1beta1.ResourcePermissions.prototype.setStat = function(value) {
  return jspb.Message.setProto3BooleanField(this, 18, value);
};


/**
 * optional bool update_grant = 19;
 * @return {boolean}
 */
proto.cs3.storage.provider.v1beta1.ResourcePermissions.prototype.getUpdateGrant = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 19, false));
};


/**
 * @param {boolean} value
 * @return {!proto.cs3.storage.provider.v1beta1.ResourcePermissions} returns this
 */
proto.cs3.storage.provider.v1beta1.ResourcePermissions.prototype.setUpdateGrant = function(value) {
  return jspb.Message.setProto3BooleanField(this, 19, value);
};


/**
 * optional bool deny_grant = 20;
 * @return {boolean}
 */
proto.cs3.storage.provider.v1beta1.ResourcePermissions.prototype.getDenyGrant = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 20, false));
};


/**
 * @param {boolean} value
 * @return {!proto.cs3.storage.provider.v1beta1.ResourcePermissions} returns this
 */
proto.cs3.storage.provider.v1beta1.ResourcePermissions.prototype.setDenyGrant = function(value) {
  return jspb.Message.setProto3BooleanField(this, 20, value);
};


