// source: cs3/ocm/provider/v1beta1/resources.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.cs3.ocm.provider.v1beta1.ServiceEndpoint');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Map');
goog.require('jspb.Message');
goog.require('proto.cs3.ocm.provider.v1beta1.ServiceType');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cs3.ocm.provider.v1beta1.ServiceEndpoint = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cs3.ocm.provider.v1beta1.ServiceEndpoint, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.displayName = 'proto.cs3.ocm.provider.v1beta1.ServiceEndpoint';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.prototype.toObject = function(opt_includeInstance) {
  return proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cs3.ocm.provider.v1beta1.ServiceEndpoint} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: (f = msg.getType()) && proto.cs3.ocm.provider.v1beta1.ServiceType.toObject(includeInstance, f),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    path: jspb.Message.getFieldWithDefault(msg, 3, ""),
    isMonitored: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
    propertiesMap: (f = msg.getPropertiesMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cs3.ocm.provider.v1beta1.ServiceEndpoint}
 */
proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cs3.ocm.provider.v1beta1.ServiceEndpoint;
  return proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cs3.ocm.provider.v1beta1.ServiceEndpoint} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cs3.ocm.provider.v1beta1.ServiceEndpoint}
 */
proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.cs3.ocm.provider.v1beta1.ServiceType;
      reader.readMessage(value,proto.cs3.ocm.provider.v1beta1.ServiceType.deserializeBinaryFromReader);
      msg.setType(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setPath(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsMonitored(value);
      break;
    case 5:
      var value = msg.getPropertiesMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cs3.ocm.provider.v1beta1.ServiceEndpoint} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.cs3.ocm.provider.v1beta1.ServiceType.serializeBinaryToWriter
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPath();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getIsMonitored();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getPropertiesMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(5, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
};


/**
 * optional ServiceType type = 1;
 * @return {?proto.cs3.ocm.provider.v1beta1.ServiceType}
 */
proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.prototype.getType = function() {
  return /** @type{?proto.cs3.ocm.provider.v1beta1.ServiceType} */ (
    jspb.Message.getWrapperField(this, proto.cs3.ocm.provider.v1beta1.ServiceType, 1));
};


/**
 * @param {?proto.cs3.ocm.provider.v1beta1.ServiceType|undefined} value
 * @return {!proto.cs3.ocm.provider.v1beta1.ServiceEndpoint} returns this
*/
proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.prototype.setType = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.ocm.provider.v1beta1.ServiceEndpoint} returns this
 */
proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.prototype.clearType = function() {
  return this.setType(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.prototype.hasType = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.cs3.ocm.provider.v1beta1.ServiceEndpoint} returns this
 */
proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string path = 3;
 * @return {string}
 */
proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.prototype.getPath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.cs3.ocm.provider.v1beta1.ServiceEndpoint} returns this
 */
proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.prototype.setPath = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional bool is_monitored = 4;
 * @return {boolean}
 */
proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.prototype.getIsMonitored = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.cs3.ocm.provider.v1beta1.ServiceEndpoint} returns this
 */
proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.prototype.setIsMonitored = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * map<string, string> properties = 5;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.prototype.getPropertiesMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 5, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.cs3.ocm.provider.v1beta1.ServiceEndpoint} returns this
 */
proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.prototype.clearPropertiesMap = function() {
  this.getPropertiesMap().clear();
  return this;
};


