// source: cs3/ocm/provider/v1beta1/resources.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.cs3.ocm.provider.v1beta1.Service');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.cs3.ocm.provider.v1beta1.ServiceEndpoint');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cs3.ocm.provider.v1beta1.Service = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.cs3.ocm.provider.v1beta1.Service.repeatedFields_, null);
};
goog.inherits(proto.cs3.ocm.provider.v1beta1.Service, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cs3.ocm.provider.v1beta1.Service.displayName = 'proto.cs3.ocm.provider.v1beta1.Service';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.cs3.ocm.provider.v1beta1.Service.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cs3.ocm.provider.v1beta1.Service.prototype.toObject = function(opt_includeInstance) {
  return proto.cs3.ocm.provider.v1beta1.Service.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cs3.ocm.provider.v1beta1.Service} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.ocm.provider.v1beta1.Service.toObject = function(includeInstance, msg) {
  var f, obj = {
    host: jspb.Message.getFieldWithDefault(msg, 1, ""),
    endpoint: (f = msg.getEndpoint()) && proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.toObject(includeInstance, f),
    apiVersion: jspb.Message.getFieldWithDefault(msg, 3, ""),
    additionalEndpointsList: jspb.Message.toObjectList(msg.getAdditionalEndpointsList(),
    proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cs3.ocm.provider.v1beta1.Service}
 */
proto.cs3.ocm.provider.v1beta1.Service.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cs3.ocm.provider.v1beta1.Service;
  return proto.cs3.ocm.provider.v1beta1.Service.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cs3.ocm.provider.v1beta1.Service} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cs3.ocm.provider.v1beta1.Service}
 */
proto.cs3.ocm.provider.v1beta1.Service.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setHost(value);
      break;
    case 2:
      var value = new proto.cs3.ocm.provider.v1beta1.ServiceEndpoint;
      reader.readMessage(value,proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.deserializeBinaryFromReader);
      msg.setEndpoint(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setApiVersion(value);
      break;
    case 4:
      var value = new proto.cs3.ocm.provider.v1beta1.ServiceEndpoint;
      reader.readMessage(value,proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.deserializeBinaryFromReader);
      msg.addAdditionalEndpoints(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cs3.ocm.provider.v1beta1.Service.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cs3.ocm.provider.v1beta1.Service.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cs3.ocm.provider.v1beta1.Service} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.ocm.provider.v1beta1.Service.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHost();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getEndpoint();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.serializeBinaryToWriter
    );
  }
  f = message.getApiVersion();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getAdditionalEndpointsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.serializeBinaryToWriter
    );
  }
};


/**
 * optional string host = 1;
 * @return {string}
 */
proto.cs3.ocm.provider.v1beta1.Service.prototype.getHost = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.cs3.ocm.provider.v1beta1.Service} returns this
 */
proto.cs3.ocm.provider.v1beta1.Service.prototype.setHost = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional ServiceEndpoint endpoint = 2;
 * @return {?proto.cs3.ocm.provider.v1beta1.ServiceEndpoint}
 */
proto.cs3.ocm.provider.v1beta1.Service.prototype.getEndpoint = function() {
  return /** @type{?proto.cs3.ocm.provider.v1beta1.ServiceEndpoint} */ (
    jspb.Message.getWrapperField(this, proto.cs3.ocm.provider.v1beta1.ServiceEndpoint, 2));
};


/**
 * @param {?proto.cs3.ocm.provider.v1beta1.ServiceEndpoint|undefined} value
 * @return {!proto.cs3.ocm.provider.v1beta1.Service} returns this
*/
proto.cs3.ocm.provider.v1beta1.Service.prototype.setEndpoint = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.ocm.provider.v1beta1.Service} returns this
 */
proto.cs3.ocm.provider.v1beta1.Service.prototype.clearEndpoint = function() {
  return this.setEndpoint(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.ocm.provider.v1beta1.Service.prototype.hasEndpoint = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string api_version = 3;
 * @return {string}
 */
proto.cs3.ocm.provider.v1beta1.Service.prototype.getApiVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.cs3.ocm.provider.v1beta1.Service} returns this
 */
proto.cs3.ocm.provider.v1beta1.Service.prototype.setApiVersion = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * repeated ServiceEndpoint additional_endpoints = 4;
 * @return {!Array<!proto.cs3.ocm.provider.v1beta1.ServiceEndpoint>}
 */
proto.cs3.ocm.provider.v1beta1.Service.prototype.getAdditionalEndpointsList = function() {
  return /** @type{!Array<!proto.cs3.ocm.provider.v1beta1.ServiceEndpoint>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.cs3.ocm.provider.v1beta1.ServiceEndpoint, 4));
};


/**
 * @param {!Array<!proto.cs3.ocm.provider.v1beta1.ServiceEndpoint>} value
 * @return {!proto.cs3.ocm.provider.v1beta1.Service} returns this
*/
proto.cs3.ocm.provider.v1beta1.Service.prototype.setAdditionalEndpointsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.cs3.ocm.provider.v1beta1.ServiceEndpoint=} opt_value
 * @param {number=} opt_index
 * @return {!proto.cs3.ocm.provider.v1beta1.ServiceEndpoint}
 */
proto.cs3.ocm.provider.v1beta1.Service.prototype.addAdditionalEndpoints = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.cs3.ocm.provider.v1beta1.ServiceEndpoint, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.cs3.ocm.provider.v1beta1.Service} returns this
 */
proto.cs3.ocm.provider.v1beta1.Service.prototype.clearAdditionalEndpointsList = function() {
  return this.setAdditionalEndpointsList([]);
};


