// source: cs3/storage/provider/v1beta1/resources.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.cs3.storage.provider.v1beta1.SpaceRole');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.cs3.storage.provider.v1beta1.Grantee');
goog.require('proto.cs3.storage.provider.v1beta1.ResourcePermissions');
goog.require('proto.cs3.types.v1beta1.Opaque');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cs3.storage.provider.v1beta1.SpaceRole = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.cs3.storage.provider.v1beta1.SpaceRole.repeatedFields_, null);
};
goog.inherits(proto.cs3.storage.provider.v1beta1.SpaceRole, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cs3.storage.provider.v1beta1.SpaceRole.displayName = 'proto.cs3.storage.provider.v1beta1.SpaceRole';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.cs3.storage.provider.v1beta1.SpaceRole.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cs3.storage.provider.v1beta1.SpaceRole.prototype.toObject = function(opt_includeInstance) {
  return proto.cs3.storage.provider.v1beta1.SpaceRole.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cs3.storage.provider.v1beta1.SpaceRole} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.storage.provider.v1beta1.SpaceRole.toObject = function(includeInstance, msg) {
  var f, obj = {
    opaque: (f = msg.getOpaque()) && proto.cs3.types.v1beta1.Opaque.toObject(includeInstance, f),
    rolename: jspb.Message.getFieldWithDefault(msg, 2, ""),
    permissionSet: (f = msg.getPermissionSet()) && proto.cs3.storage.provider.v1beta1.ResourcePermissions.toObject(includeInstance, f),
    recipientsList: jspb.Message.toObjectList(msg.getRecipientsList(),
    proto.cs3.storage.provider.v1beta1.Grantee.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cs3.storage.provider.v1beta1.SpaceRole}
 */
proto.cs3.storage.provider.v1beta1.SpaceRole.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cs3.storage.provider.v1beta1.SpaceRole;
  return proto.cs3.storage.provider.v1beta1.SpaceRole.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cs3.storage.provider.v1beta1.SpaceRole} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cs3.storage.provider.v1beta1.SpaceRole}
 */
proto.cs3.storage.provider.v1beta1.SpaceRole.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.cs3.types.v1beta1.Opaque;
      reader.readMessage(value,proto.cs3.types.v1beta1.Opaque.deserializeBinaryFromReader);
      msg.setOpaque(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setRolename(value);
      break;
    case 3:
      var value = new proto.cs3.storage.provider.v1beta1.ResourcePermissions;
      reader.readMessage(value,proto.cs3.storage.provider.v1beta1.ResourcePermissions.deserializeBinaryFromReader);
      msg.setPermissionSet(value);
      break;
    case 4:
      var value = new proto.cs3.storage.provider.v1beta1.Grantee;
      reader.readMessage(value,proto.cs3.storage.provider.v1beta1.Grantee.deserializeBinaryFromReader);
      msg.addRecipients(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cs3.storage.provider.v1beta1.SpaceRole.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cs3.storage.provider.v1beta1.SpaceRole.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cs3.storage.provider.v1beta1.SpaceRole} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.storage.provider.v1beta1.SpaceRole.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOpaque();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.cs3.types.v1beta1.Opaque.serializeBinaryToWriter
    );
  }
  f = message.getRolename();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPermissionSet();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.cs3.storage.provider.v1beta1.ResourcePermissions.serializeBinaryToWriter
    );
  }
  f = message.getRecipientsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.cs3.storage.provider.v1beta1.Grantee.serializeBinaryToWriter
    );
  }
};


/**
 * optional cs3.types.v1beta1.Opaque opaque = 1;
 * @return {?proto.cs3.types.v1beta1.Opaque}
 */
proto.cs3.storage.provider.v1beta1.SpaceRole.prototype.getOpaque = function() {
  return /** @type{?proto.cs3.types.v1beta1.Opaque} */ (
    jspb.Message.getWrapperField(this, proto.cs3.types.v1beta1.Opaque, 1));
};


/**
 * @param {?proto.cs3.types.v1beta1.Opaque|undefined} value
 * @return {!proto.cs3.storage.provider.v1beta1.SpaceRole} returns this
*/
proto.cs3.storage.provider.v1beta1.SpaceRole.prototype.setOpaque = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.storage.provider.v1beta1.SpaceRole} returns this
 */
proto.cs3.storage.provider.v1beta1.SpaceRole.prototype.clearOpaque = function() {
  return this.setOpaque(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.storage.provider.v1beta1.SpaceRole.prototype.hasOpaque = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string RoleName = 2;
 * @return {string}
 */
proto.cs3.storage.provider.v1beta1.SpaceRole.prototype.getRolename = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.cs3.storage.provider.v1beta1.SpaceRole} returns this
 */
proto.cs3.storage.provider.v1beta1.SpaceRole.prototype.setRolename = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional ResourcePermissions permission_set = 3;
 * @return {?proto.cs3.storage.provider.v1beta1.ResourcePermissions}
 */
proto.cs3.storage.provider.v1beta1.SpaceRole.prototype.getPermissionSet = function() {
  return /** @type{?proto.cs3.storage.provider.v1beta1.ResourcePermissions} */ (
    jspb.Message.getWrapperField(this, proto.cs3.storage.provider.v1beta1.ResourcePermissions, 3));
};


/**
 * @param {?proto.cs3.storage.provider.v1beta1.ResourcePermissions|undefined} value
 * @return {!proto.cs3.storage.provider.v1beta1.SpaceRole} returns this
*/
proto.cs3.storage.provider.v1beta1.SpaceRole.prototype.setPermissionSet = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.storage.provider.v1beta1.SpaceRole} returns this
 */
proto.cs3.storage.provider.v1beta1.SpaceRole.prototype.clearPermissionSet = function() {
  return this.setPermissionSet(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.storage.provider.v1beta1.SpaceRole.prototype.hasPermissionSet = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * repeated Grantee recipients = 4;
 * @return {!Array<!proto.cs3.storage.provider.v1beta1.Grantee>}
 */
proto.cs3.storage.provider.v1beta1.SpaceRole.prototype.getRecipientsList = function() {
  return /** @type{!Array<!proto.cs3.storage.provider.v1beta1.Grantee>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.cs3.storage.provider.v1beta1.Grantee, 4));
};


/**
 * @param {!Array<!proto.cs3.storage.provider.v1beta1.Grantee>} value
 * @return {!proto.cs3.storage.provider.v1beta1.SpaceRole} returns this
*/
proto.cs3.storage.provider.v1beta1.SpaceRole.prototype.setRecipientsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.cs3.storage.provider.v1beta1.Grantee=} opt_value
 * @param {number=} opt_index
 * @return {!proto.cs3.storage.provider.v1beta1.Grantee}
 */
proto.cs3.storage.provider.v1beta1.SpaceRole.prototype.addRecipients = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.cs3.storage.provider.v1beta1.Grantee, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.cs3.storage.provider.v1beta1.SpaceRole} returns this
 */
proto.cs3.storage.provider.v1beta1.SpaceRole.prototype.clearRecipientsList = function() {
  return this.setRecipientsList([]);
};


