// source: cs3/sharing/ocm/v1beta1/resources.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.cs3.sharing.ocm.v1beta1.WebappProtocol');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.cs3.storage.provider.v1beta1.ResourcePermissions');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cs3.sharing.ocm.v1beta1.WebappProtocol = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.cs3.sharing.ocm.v1beta1.WebappProtocol.repeatedFields_, null);
};
goog.inherits(proto.cs3.sharing.ocm.v1beta1.WebappProtocol, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cs3.sharing.ocm.v1beta1.WebappProtocol.displayName = 'proto.cs3.sharing.ocm.v1beta1.WebappProtocol';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.cs3.sharing.ocm.v1beta1.WebappProtocol.repeatedFields_ = [4,5,8];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cs3.sharing.ocm.v1beta1.WebappProtocol.prototype.toObject = function(opt_includeInstance) {
  return proto.cs3.sharing.ocm.v1beta1.WebappProtocol.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cs3.sharing.ocm.v1beta1.WebappProtocol} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.sharing.ocm.v1beta1.WebappProtocol.toObject = function(includeInstance, msg) {
  var f, obj = {
    sharedSecret: jspb.Message.getFieldWithDefault(msg, 1, ""),
    sharePermissions: (f = msg.getSharePermissions()) && proto.cs3.storage.provider.v1beta1.ResourcePermissions.toObject(includeInstance, f),
    uri: jspb.Message.getFieldWithDefault(msg, 3, ""),
    requirementsList: (f = jspb.Message.getRepeatedField(msg, 4)) == null ? undefined : f,
    targetsList: (f = jspb.Message.getRepeatedField(msg, 5)) == null ? undefined : f,
    appName: jspb.Message.getFieldWithDefault(msg, 6, ""),
    appIconHint: jspb.Message.getFieldWithDefault(msg, 7, ""),
    mediaTypesList: (f = jspb.Message.getRepeatedField(msg, 8)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cs3.sharing.ocm.v1beta1.WebappProtocol}
 */
proto.cs3.sharing.ocm.v1beta1.WebappProtocol.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cs3.sharing.ocm.v1beta1.WebappProtocol;
  return proto.cs3.sharing.ocm.v1beta1.WebappProtocol.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cs3.sharing.ocm.v1beta1.WebappProtocol} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cs3.sharing.ocm.v1beta1.WebappProtocol}
 */
proto.cs3.sharing.ocm.v1beta1.WebappProtocol.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSharedSecret(value);
      break;
    case 2:
      var value = new proto.cs3.storage.provider.v1beta1.ResourcePermissions;
      reader.readMessage(value,proto.cs3.storage.provider.v1beta1.ResourcePermissions.deserializeBinaryFromReader);
      msg.setSharePermissions(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setUri(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.addRequirements(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.addTargets(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setAppName(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setAppIconHint(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.addMediaTypes(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cs3.sharing.ocm.v1beta1.WebappProtocol.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cs3.sharing.ocm.v1beta1.WebappProtocol.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cs3.sharing.ocm.v1beta1.WebappProtocol} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.sharing.ocm.v1beta1.WebappProtocol.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSharedSecret();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSharePermissions();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.cs3.storage.provider.v1beta1.ResourcePermissions.serializeBinaryToWriter
    );
  }
  f = message.getUri();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getRequirementsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      4,
      f
    );
  }
  f = message.getTargetsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      5,
      f
    );
  }
  f = message.getAppName();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getAppIconHint();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getMediaTypesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      8,
      f
    );
  }
};


/**
 * optional string shared_secret = 1;
 * @return {string}
 */
proto.cs3.sharing.ocm.v1beta1.WebappProtocol.prototype.getSharedSecret = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.cs3.sharing.ocm.v1beta1.WebappProtocol} returns this
 */
proto.cs3.sharing.ocm.v1beta1.WebappProtocol.prototype.setSharedSecret = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional cs3.storage.provider.v1beta1.ResourcePermissions share_permissions = 2;
 * @return {?proto.cs3.storage.provider.v1beta1.ResourcePermissions}
 */
proto.cs3.sharing.ocm.v1beta1.WebappProtocol.prototype.getSharePermissions = function() {
  return /** @type{?proto.cs3.storage.provider.v1beta1.ResourcePermissions} */ (
    jspb.Message.getWrapperField(this, proto.cs3.storage.provider.v1beta1.ResourcePermissions, 2));
};


/**
 * @param {?proto.cs3.storage.provider.v1beta1.ResourcePermissions|undefined} value
 * @return {!proto.cs3.sharing.ocm.v1beta1.WebappProtocol} returns this
*/
proto.cs3.sharing.ocm.v1beta1.WebappProtocol.prototype.setSharePermissions = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.sharing.ocm.v1beta1.WebappProtocol} returns this
 */
proto.cs3.sharing.ocm.v1beta1.WebappProtocol.prototype.clearSharePermissions = function() {
  return this.setSharePermissions(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.sharing.ocm.v1beta1.WebappProtocol.prototype.hasSharePermissions = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string uri = 3;
 * @return {string}
 */
proto.cs3.sharing.ocm.v1beta1.WebappProtocol.prototype.getUri = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.cs3.sharing.ocm.v1beta1.WebappProtocol} returns this
 */
proto.cs3.sharing.ocm.v1beta1.WebappProtocol.prototype.setUri = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * repeated string requirements = 4;
 * @return {!Array<string>}
 */
proto.cs3.sharing.ocm.v1beta1.WebappProtocol.prototype.getRequirementsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 4));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.cs3.sharing.ocm.v1beta1.WebappProtocol} returns this
 */
proto.cs3.sharing.ocm.v1beta1.WebappProtocol.prototype.setRequirementsList = function(value) {
  return jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.cs3.sharing.ocm.v1beta1.WebappProtocol} returns this
 */
proto.cs3.sharing.ocm.v1beta1.WebappProtocol.prototype.addRequirements = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.cs3.sharing.ocm.v1beta1.WebappProtocol} returns this
 */
proto.cs3.sharing.ocm.v1beta1.WebappProtocol.prototype.clearRequirementsList = function() {
  return this.setRequirementsList([]);
};


/**
 * repeated string targets = 5;
 * @return {!Array<string>}
 */
proto.cs3.sharing.ocm.v1beta1.WebappProtocol.prototype.getTargetsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 5));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.cs3.sharing.ocm.v1beta1.WebappProtocol} returns this
 */
proto.cs3.sharing.ocm.v1beta1.WebappProtocol.prototype.setTargetsList = function(value) {
  return jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.cs3.sharing.ocm.v1beta1.WebappProtocol} returns this
 */
proto.cs3.sharing.ocm.v1beta1.WebappProtocol.prototype.addTargets = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.cs3.sharing.ocm.v1beta1.WebappProtocol} returns this
 */
proto.cs3.sharing.ocm.v1beta1.WebappProtocol.prototype.clearTargetsList = function() {
  return this.setTargetsList([]);
};


/**
 * optional string app_name = 6;
 * @return {string}
 */
proto.cs3.sharing.ocm.v1beta1.WebappProtocol.prototype.getAppName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.cs3.sharing.ocm.v1beta1.WebappProtocol} returns this
 */
proto.cs3.sharing.ocm.v1beta1.WebappProtocol.prototype.setAppName = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string app_icon_hint = 7;
 * @return {string}
 */
proto.cs3.sharing.ocm.v1beta1.WebappProtocol.prototype.getAppIconHint = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.cs3.sharing.ocm.v1beta1.WebappProtocol} returns this
 */
proto.cs3.sharing.ocm.v1beta1.WebappProtocol.prototype.setAppIconHint = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * repeated string media_types = 8;
 * @return {!Array<string>}
 */
proto.cs3.sharing.ocm.v1beta1.WebappProtocol.prototype.getMediaTypesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 8));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.cs3.sharing.ocm.v1beta1.WebappProtocol} returns this
 */
proto.cs3.sharing.ocm.v1beta1.WebappProtocol.prototype.setMediaTypesList = function(value) {
  return jspb.Message.setField(this, 8, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.cs3.sharing.ocm.v1beta1.WebappProtocol} returns this
 */
proto.cs3.sharing.ocm.v1beta1.WebappProtocol.prototype.addMediaTypes = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 8, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.cs3.sharing.ocm.v1beta1.WebappProtocol} returns this
 */
proto.cs3.sharing.ocm.v1beta1.WebappProtocol.prototype.clearMediaTypesList = function() {
  return this.setMediaTypesList([]);
};


