/**
 * @fileoverview gRPC-Web generated client stub for cs3.ocm.core.v1beta1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v0.0.0
// source: cs3/ocm/core/v1beta1/ocm_core_api.proto


/* eslint-disable */
// @ts-nocheck


goog.provide('proto.cs3.ocm.core.v1beta1.OcmCoreAPIClient');
goog.provide('proto.cs3.ocm.core.v1beta1.OcmCoreAPIPromiseClient');

goog.require('grpc.web.MethodDescriptor');
goog.require('grpc.web.MethodType');
goog.require('grpc.web.GrpcWebClientBase');
goog.require('grpc.web.AbstractClientBase');
goog.require('grpc.web.ClientReadableStream');
goog.require('grpc.web.RpcError');
goog.require('proto.cs3.ocm.core.v1beta1.CreateOCMCoreShareRequest');
goog.require('proto.cs3.ocm.core.v1beta1.CreateOCMCoreShareResponse');
goog.require('proto.cs3.ocm.core.v1beta1.DeleteOCMCoreShareRequest');
goog.require('proto.cs3.ocm.core.v1beta1.DeleteOCMCoreShareResponse');
goog.require('proto.cs3.ocm.core.v1beta1.UpdateOCMCoreShareRequest');
goog.require('proto.cs3.ocm.core.v1beta1.UpdateOCMCoreShareResponse');

goog.requireType('grpc.web.ClientOptions');



goog.scope(function() {

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.cs3.ocm.core.v1beta1.OcmCoreAPIClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.cs3.ocm.core.v1beta1.OcmCoreAPIPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.ocm.core.v1beta1.CreateOCMCoreShareRequest,
 *   !proto.cs3.ocm.core.v1beta1.CreateOCMCoreShareResponse>}
 */
const methodDescriptor_OcmCoreAPI_CreateOCMCoreShare = new grpc.web.MethodDescriptor(
  '/cs3.ocm.core.v1beta1.OcmCoreAPI/CreateOCMCoreShare',
  grpc.web.MethodType.UNARY,
  proto.cs3.ocm.core.v1beta1.CreateOCMCoreShareRequest,
  proto.cs3.ocm.core.v1beta1.CreateOCMCoreShareResponse,
  /**
   * @param {!proto.cs3.ocm.core.v1beta1.CreateOCMCoreShareRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.ocm.core.v1beta1.CreateOCMCoreShareResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.ocm.core.v1beta1.CreateOCMCoreShareRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cs3.ocm.core.v1beta1.CreateOCMCoreShareResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.ocm.core.v1beta1.CreateOCMCoreShareResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cs3.ocm.core.v1beta1.OcmCoreAPIClient.prototype.createOCMCoreShare =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cs3.ocm.core.v1beta1.OcmCoreAPI/CreateOCMCoreShare',
      request,
      metadata || {},
      methodDescriptor_OcmCoreAPI_CreateOCMCoreShare,
      callback);
};


/**
 * @param {!proto.cs3.ocm.core.v1beta1.CreateOCMCoreShareRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cs3.ocm.core.v1beta1.CreateOCMCoreShareResponse>}
 *     Promise that resolves to the response
 */
proto.cs3.ocm.core.v1beta1.OcmCoreAPIPromiseClient.prototype.createOCMCoreShare =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cs3.ocm.core.v1beta1.OcmCoreAPI/CreateOCMCoreShare',
      request,
      metadata || {},
      methodDescriptor_OcmCoreAPI_CreateOCMCoreShare);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.ocm.core.v1beta1.UpdateOCMCoreShareRequest,
 *   !proto.cs3.ocm.core.v1beta1.UpdateOCMCoreShareResponse>}
 */
const methodDescriptor_OcmCoreAPI_UpdateOCMCoreShare = new grpc.web.MethodDescriptor(
  '/cs3.ocm.core.v1beta1.OcmCoreAPI/UpdateOCMCoreShare',
  grpc.web.MethodType.UNARY,
  proto.cs3.ocm.core.v1beta1.UpdateOCMCoreShareRequest,
  proto.cs3.ocm.core.v1beta1.UpdateOCMCoreShareResponse,
  /**
   * @param {!proto.cs3.ocm.core.v1beta1.UpdateOCMCoreShareRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.ocm.core.v1beta1.UpdateOCMCoreShareResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.ocm.core.v1beta1.UpdateOCMCoreShareRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cs3.ocm.core.v1beta1.UpdateOCMCoreShareResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.ocm.core.v1beta1.UpdateOCMCoreShareResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cs3.ocm.core.v1beta1.OcmCoreAPIClient.prototype.updateOCMCoreShare =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cs3.ocm.core.v1beta1.OcmCoreAPI/UpdateOCMCoreShare',
      request,
      metadata || {},
      methodDescriptor_OcmCoreAPI_UpdateOCMCoreShare,
      callback);
};


/**
 * @param {!proto.cs3.ocm.core.v1beta1.UpdateOCMCoreShareRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cs3.ocm.core.v1beta1.UpdateOCMCoreShareResponse>}
 *     Promise that resolves to the response
 */
proto.cs3.ocm.core.v1beta1.OcmCoreAPIPromiseClient.prototype.updateOCMCoreShare =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cs3.ocm.core.v1beta1.OcmCoreAPI/UpdateOCMCoreShare',
      request,
      metadata || {},
      methodDescriptor_OcmCoreAPI_UpdateOCMCoreShare);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.ocm.core.v1beta1.DeleteOCMCoreShareRequest,
 *   !proto.cs3.ocm.core.v1beta1.DeleteOCMCoreShareResponse>}
 */
const methodDescriptor_OcmCoreAPI_DeleteOCMCoreShare = new grpc.web.MethodDescriptor(
  '/cs3.ocm.core.v1beta1.OcmCoreAPI/DeleteOCMCoreShare',
  grpc.web.MethodType.UNARY,
  proto.cs3.ocm.core.v1beta1.DeleteOCMCoreShareRequest,
  proto.cs3.ocm.core.v1beta1.DeleteOCMCoreShareResponse,
  /**
   * @param {!proto.cs3.ocm.core.v1beta1.DeleteOCMCoreShareRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.ocm.core.v1beta1.DeleteOCMCoreShareResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.ocm.core.v1beta1.DeleteOCMCoreShareRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cs3.ocm.core.v1beta1.DeleteOCMCoreShareResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.ocm.core.v1beta1.DeleteOCMCoreShareResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cs3.ocm.core.v1beta1.OcmCoreAPIClient.prototype.deleteOCMCoreShare =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cs3.ocm.core.v1beta1.OcmCoreAPI/DeleteOCMCoreShare',
      request,
      metadata || {},
      methodDescriptor_OcmCoreAPI_DeleteOCMCoreShare,
      callback);
};


/**
 * @param {!proto.cs3.ocm.core.v1beta1.DeleteOCMCoreShareRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cs3.ocm.core.v1beta1.DeleteOCMCoreShareResponse>}
 *     Promise that resolves to the response
 */
proto.cs3.ocm.core.v1beta1.OcmCoreAPIPromiseClient.prototype.deleteOCMCoreShare =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cs3.ocm.core.v1beta1.OcmCoreAPI/DeleteOCMCoreShare',
      request,
      metadata || {},
      methodDescriptor_OcmCoreAPI_DeleteOCMCoreShare);
};


}); // goog.scope

