/**
 * @fileoverview gRPC-Web generated client stub for cs3.labels.v1beta1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v0.0.0
// source: cs3/labels/v1beta1/label_api.proto


/* eslint-disable */
// @ts-nocheck


goog.provide('proto.cs3.labels.v1beta1.LabelsAPIClient');
goog.provide('proto.cs3.labels.v1beta1.LabelsAPIPromiseClient');

goog.require('grpc.web.MethodDescriptor');
goog.require('grpc.web.MethodType');
goog.require('grpc.web.GrpcWebClientBase');
goog.require('grpc.web.AbstractClientBase');
goog.require('grpc.web.ClientReadableStream');
goog.require('grpc.web.RpcError');
goog.require('proto.cs3.labels.v1beta1.AddLabelRequest');
goog.require('proto.cs3.labels.v1beta1.AddLabelResponse');
goog.require('proto.cs3.labels.v1beta1.ListLabelsRequest');
goog.require('proto.cs3.labels.v1beta1.ListLabelsResponse');
goog.require('proto.cs3.labels.v1beta1.ListResourcesForLabelRequest');
goog.require('proto.cs3.labels.v1beta1.ListResourcesForLabelResponse');
goog.require('proto.cs3.labels.v1beta1.RemoveLabelRequest');
goog.require('proto.cs3.labels.v1beta1.RemoveLabelResponse');

goog.requireType('grpc.web.ClientOptions');



goog.scope(function() {

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.cs3.labels.v1beta1.LabelsAPIClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.cs3.labels.v1beta1.LabelsAPIPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.labels.v1beta1.AddLabelRequest,
 *   !proto.cs3.labels.v1beta1.AddLabelResponse>}
 */
const methodDescriptor_LabelsAPI_AddLabel = new grpc.web.MethodDescriptor(
  '/cs3.labels.v1beta1.LabelsAPI/AddLabel',
  grpc.web.MethodType.UNARY,
  proto.cs3.labels.v1beta1.AddLabelRequest,
  proto.cs3.labels.v1beta1.AddLabelResponse,
  /**
   * @param {!proto.cs3.labels.v1beta1.AddLabelRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.labels.v1beta1.AddLabelResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.labels.v1beta1.AddLabelRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cs3.labels.v1beta1.AddLabelResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.labels.v1beta1.AddLabelResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cs3.labels.v1beta1.LabelsAPIClient.prototype.addLabel =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cs3.labels.v1beta1.LabelsAPI/AddLabel',
      request,
      metadata || {},
      methodDescriptor_LabelsAPI_AddLabel,
      callback);
};


/**
 * @param {!proto.cs3.labels.v1beta1.AddLabelRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cs3.labels.v1beta1.AddLabelResponse>}
 *     Promise that resolves to the response
 */
proto.cs3.labels.v1beta1.LabelsAPIPromiseClient.prototype.addLabel =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cs3.labels.v1beta1.LabelsAPI/AddLabel',
      request,
      metadata || {},
      methodDescriptor_LabelsAPI_AddLabel);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.labels.v1beta1.RemoveLabelRequest,
 *   !proto.cs3.labels.v1beta1.RemoveLabelResponse>}
 */
const methodDescriptor_LabelsAPI_RemoveLabel = new grpc.web.MethodDescriptor(
  '/cs3.labels.v1beta1.LabelsAPI/RemoveLabel',
  grpc.web.MethodType.UNARY,
  proto.cs3.labels.v1beta1.RemoveLabelRequest,
  proto.cs3.labels.v1beta1.RemoveLabelResponse,
  /**
   * @param {!proto.cs3.labels.v1beta1.RemoveLabelRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.labels.v1beta1.RemoveLabelResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.labels.v1beta1.RemoveLabelRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cs3.labels.v1beta1.RemoveLabelResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.labels.v1beta1.RemoveLabelResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cs3.labels.v1beta1.LabelsAPIClient.prototype.removeLabel =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cs3.labels.v1beta1.LabelsAPI/RemoveLabel',
      request,
      metadata || {},
      methodDescriptor_LabelsAPI_RemoveLabel,
      callback);
};


/**
 * @param {!proto.cs3.labels.v1beta1.RemoveLabelRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cs3.labels.v1beta1.RemoveLabelResponse>}
 *     Promise that resolves to the response
 */
proto.cs3.labels.v1beta1.LabelsAPIPromiseClient.prototype.removeLabel =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cs3.labels.v1beta1.LabelsAPI/RemoveLabel',
      request,
      metadata || {},
      methodDescriptor_LabelsAPI_RemoveLabel);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.labels.v1beta1.ListLabelsRequest,
 *   !proto.cs3.labels.v1beta1.ListLabelsResponse>}
 */
const methodDescriptor_LabelsAPI_ListLabels = new grpc.web.MethodDescriptor(
  '/cs3.labels.v1beta1.LabelsAPI/ListLabels',
  grpc.web.MethodType.UNARY,
  proto.cs3.labels.v1beta1.ListLabelsRequest,
  proto.cs3.labels.v1beta1.ListLabelsResponse,
  /**
   * @param {!proto.cs3.labels.v1beta1.ListLabelsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.labels.v1beta1.ListLabelsResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.labels.v1beta1.ListLabelsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cs3.labels.v1beta1.ListLabelsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.labels.v1beta1.ListLabelsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cs3.labels.v1beta1.LabelsAPIClient.prototype.listLabels =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cs3.labels.v1beta1.LabelsAPI/ListLabels',
      request,
      metadata || {},
      methodDescriptor_LabelsAPI_ListLabels,
      callback);
};


/**
 * @param {!proto.cs3.labels.v1beta1.ListLabelsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cs3.labels.v1beta1.ListLabelsResponse>}
 *     Promise that resolves to the response
 */
proto.cs3.labels.v1beta1.LabelsAPIPromiseClient.prototype.listLabels =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cs3.labels.v1beta1.LabelsAPI/ListLabels',
      request,
      metadata || {},
      methodDescriptor_LabelsAPI_ListLabels);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.labels.v1beta1.ListResourcesForLabelRequest,
 *   !proto.cs3.labels.v1beta1.ListResourcesForLabelResponse>}
 */
const methodDescriptor_LabelsAPI_ListResourcesForLabel = new grpc.web.MethodDescriptor(
  '/cs3.labels.v1beta1.LabelsAPI/ListResourcesForLabel',
  grpc.web.MethodType.UNARY,
  proto.cs3.labels.v1beta1.ListResourcesForLabelRequest,
  proto.cs3.labels.v1beta1.ListResourcesForLabelResponse,
  /**
   * @param {!proto.cs3.labels.v1beta1.ListResourcesForLabelRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.labels.v1beta1.ListResourcesForLabelResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.labels.v1beta1.ListResourcesForLabelRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cs3.labels.v1beta1.ListResourcesForLabelResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.labels.v1beta1.ListResourcesForLabelResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cs3.labels.v1beta1.LabelsAPIClient.prototype.listResourcesForLabel =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cs3.labels.v1beta1.LabelsAPI/ListResourcesForLabel',
      request,
      metadata || {},
      methodDescriptor_LabelsAPI_ListResourcesForLabel,
      callback);
};


/**
 * @param {!proto.cs3.labels.v1beta1.ListResourcesForLabelRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cs3.labels.v1beta1.ListResourcesForLabelResponse>}
 *     Promise that resolves to the response
 */
proto.cs3.labels.v1beta1.LabelsAPIPromiseClient.prototype.listResourcesForLabel =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cs3.labels.v1beta1.LabelsAPI/ListResourcesForLabel',
      request,
      metadata || {},
      methodDescriptor_LabelsAPI_ListResourcesForLabel);
};


}); // goog.scope

