/**
 * @fileoverview gRPC-Web generated client stub for cs3.preferences.v1beta1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v0.0.0
// source: cs3/preferences/v1beta1/preferences_api.proto


/* eslint-disable */
// @ts-nocheck


goog.provide('proto.cs3.preferences.v1beta1.PreferencesAPIClient');
goog.provide('proto.cs3.preferences.v1beta1.PreferencesAPIPromiseClient');

goog.require('grpc.web.MethodDescriptor');
goog.require('grpc.web.MethodType');
goog.require('grpc.web.GrpcWebClientBase');
goog.require('grpc.web.AbstractClientBase');
goog.require('grpc.web.ClientReadableStream');
goog.require('grpc.web.RpcError');
goog.require('proto.cs3.preferences.v1beta1.GetKeyRequest');
goog.require('proto.cs3.preferences.v1beta1.GetKeyResponse');
goog.require('proto.cs3.preferences.v1beta1.SetKeyRequest');
goog.require('proto.cs3.preferences.v1beta1.SetKeyResponse');

goog.requireType('grpc.web.ClientOptions');



goog.scope(function() {

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.cs3.preferences.v1beta1.PreferencesAPIClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.cs3.preferences.v1beta1.PreferencesAPIPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.preferences.v1beta1.SetKeyRequest,
 *   !proto.cs3.preferences.v1beta1.SetKeyResponse>}
 */
const methodDescriptor_PreferencesAPI_SetKey = new grpc.web.MethodDescriptor(
  '/cs3.preferences.v1beta1.PreferencesAPI/SetKey',
  grpc.web.MethodType.UNARY,
  proto.cs3.preferences.v1beta1.SetKeyRequest,
  proto.cs3.preferences.v1beta1.SetKeyResponse,
  /**
   * @param {!proto.cs3.preferences.v1beta1.SetKeyRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.preferences.v1beta1.SetKeyResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.preferences.v1beta1.SetKeyRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cs3.preferences.v1beta1.SetKeyResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.preferences.v1beta1.SetKeyResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cs3.preferences.v1beta1.PreferencesAPIClient.prototype.setKey =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cs3.preferences.v1beta1.PreferencesAPI/SetKey',
      request,
      metadata || {},
      methodDescriptor_PreferencesAPI_SetKey,
      callback);
};


/**
 * @param {!proto.cs3.preferences.v1beta1.SetKeyRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cs3.preferences.v1beta1.SetKeyResponse>}
 *     Promise that resolves to the response
 */
proto.cs3.preferences.v1beta1.PreferencesAPIPromiseClient.prototype.setKey =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cs3.preferences.v1beta1.PreferencesAPI/SetKey',
      request,
      metadata || {},
      methodDescriptor_PreferencesAPI_SetKey);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.preferences.v1beta1.GetKeyRequest,
 *   !proto.cs3.preferences.v1beta1.GetKeyResponse>}
 */
const methodDescriptor_PreferencesAPI_GetKey = new grpc.web.MethodDescriptor(
  '/cs3.preferences.v1beta1.PreferencesAPI/GetKey',
  grpc.web.MethodType.UNARY,
  proto.cs3.preferences.v1beta1.GetKeyRequest,
  proto.cs3.preferences.v1beta1.GetKeyResponse,
  /**
   * @param {!proto.cs3.preferences.v1beta1.GetKeyRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.preferences.v1beta1.GetKeyResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.preferences.v1beta1.GetKeyRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cs3.preferences.v1beta1.GetKeyResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.preferences.v1beta1.GetKeyResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cs3.preferences.v1beta1.PreferencesAPIClient.prototype.getKey =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cs3.preferences.v1beta1.PreferencesAPI/GetKey',
      request,
      metadata || {},
      methodDescriptor_PreferencesAPI_GetKey,
      callback);
};


/**
 * @param {!proto.cs3.preferences.v1beta1.GetKeyRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cs3.preferences.v1beta1.GetKeyResponse>}
 *     Promise that resolves to the response
 */
proto.cs3.preferences.v1beta1.PreferencesAPIPromiseClient.prototype.getKey =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cs3.preferences.v1beta1.PreferencesAPI/GetKey',
      request,
      metadata || {},
      methodDescriptor_PreferencesAPI_GetKey);
};


}); // goog.scope

