/**
 * @fileoverview gRPC-Web generated client stub for cs3.auth.registry.v1beta1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v0.0.0
// source: cs3/auth/registry/v1beta1/registry_api.proto


/* eslint-disable */
// @ts-nocheck


goog.provide('proto.cs3.auth.registry.v1beta1.RegistryAPIClient');
goog.provide('proto.cs3.auth.registry.v1beta1.RegistryAPIPromiseClient');

goog.require('grpc.web.MethodDescriptor');
goog.require('grpc.web.MethodType');
goog.require('grpc.web.GrpcWebClientBase');
goog.require('grpc.web.AbstractClientBase');
goog.require('grpc.web.ClientReadableStream');
goog.require('grpc.web.RpcError');
goog.require('proto.cs3.auth.registry.v1beta1.GetAuthProvidersRequest');
goog.require('proto.cs3.auth.registry.v1beta1.GetAuthProvidersResponse');
goog.require('proto.cs3.auth.registry.v1beta1.ListAuthProvidersRequest');
goog.require('proto.cs3.auth.registry.v1beta1.ListAuthProvidersResponse');

goog.requireType('grpc.web.ClientOptions');



goog.scope(function() {

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.cs3.auth.registry.v1beta1.RegistryAPIClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.cs3.auth.registry.v1beta1.RegistryAPIPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.auth.registry.v1beta1.GetAuthProvidersRequest,
 *   !proto.cs3.auth.registry.v1beta1.GetAuthProvidersResponse>}
 */
const methodDescriptor_RegistryAPI_GetAuthProviders = new grpc.web.MethodDescriptor(
  '/cs3.auth.registry.v1beta1.RegistryAPI/GetAuthProviders',
  grpc.web.MethodType.UNARY,
  proto.cs3.auth.registry.v1beta1.GetAuthProvidersRequest,
  proto.cs3.auth.registry.v1beta1.GetAuthProvidersResponse,
  /**
   * @param {!proto.cs3.auth.registry.v1beta1.GetAuthProvidersRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.auth.registry.v1beta1.GetAuthProvidersResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.auth.registry.v1beta1.GetAuthProvidersRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cs3.auth.registry.v1beta1.GetAuthProvidersResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.auth.registry.v1beta1.GetAuthProvidersResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cs3.auth.registry.v1beta1.RegistryAPIClient.prototype.getAuthProviders =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cs3.auth.registry.v1beta1.RegistryAPI/GetAuthProviders',
      request,
      metadata || {},
      methodDescriptor_RegistryAPI_GetAuthProviders,
      callback);
};


/**
 * @param {!proto.cs3.auth.registry.v1beta1.GetAuthProvidersRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cs3.auth.registry.v1beta1.GetAuthProvidersResponse>}
 *     Promise that resolves to the response
 */
proto.cs3.auth.registry.v1beta1.RegistryAPIPromiseClient.prototype.getAuthProviders =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cs3.auth.registry.v1beta1.RegistryAPI/GetAuthProviders',
      request,
      metadata || {},
      methodDescriptor_RegistryAPI_GetAuthProviders);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.auth.registry.v1beta1.ListAuthProvidersRequest,
 *   !proto.cs3.auth.registry.v1beta1.ListAuthProvidersResponse>}
 */
const methodDescriptor_RegistryAPI_ListAuthProviders = new grpc.web.MethodDescriptor(
  '/cs3.auth.registry.v1beta1.RegistryAPI/ListAuthProviders',
  grpc.web.MethodType.UNARY,
  proto.cs3.auth.registry.v1beta1.ListAuthProvidersRequest,
  proto.cs3.auth.registry.v1beta1.ListAuthProvidersResponse,
  /**
   * @param {!proto.cs3.auth.registry.v1beta1.ListAuthProvidersRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.auth.registry.v1beta1.ListAuthProvidersResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.auth.registry.v1beta1.ListAuthProvidersRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cs3.auth.registry.v1beta1.ListAuthProvidersResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.auth.registry.v1beta1.ListAuthProvidersResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cs3.auth.registry.v1beta1.RegistryAPIClient.prototype.listAuthProviders =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cs3.auth.registry.v1beta1.RegistryAPI/ListAuthProviders',
      request,
      metadata || {},
      methodDescriptor_RegistryAPI_ListAuthProviders,
      callback);
};


/**
 * @param {!proto.cs3.auth.registry.v1beta1.ListAuthProvidersRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cs3.auth.registry.v1beta1.ListAuthProvidersResponse>}
 *     Promise that resolves to the response
 */
proto.cs3.auth.registry.v1beta1.RegistryAPIPromiseClient.prototype.listAuthProviders =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cs3.auth.registry.v1beta1.RegistryAPI/ListAuthProviders',
      request,
      metadata || {},
      methodDescriptor_RegistryAPI_ListAuthProviders);
};


}); // goog.scope

