/**
 * @fileoverview gRPC-Web generated client stub for cs3.auth.applications.v1beta1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v0.0.0
// source: cs3/auth/applications/v1beta1/applications_api.proto


/* eslint-disable */
// @ts-nocheck


goog.provide('proto.cs3.auth.applications.v1beta1.ApplicationsAPIClient');
goog.provide('proto.cs3.auth.applications.v1beta1.ApplicationsAPIPromiseClient');

goog.require('grpc.web.MethodDescriptor');
goog.require('grpc.web.MethodType');
goog.require('grpc.web.GrpcWebClientBase');
goog.require('grpc.web.AbstractClientBase');
goog.require('grpc.web.ClientReadableStream');
goog.require('grpc.web.RpcError');
goog.require('proto.cs3.auth.applications.v1beta1.GenerateAppPasswordRequest');
goog.require('proto.cs3.auth.applications.v1beta1.GenerateAppPasswordResponse');
goog.require('proto.cs3.auth.applications.v1beta1.GetAppPasswordRequest');
goog.require('proto.cs3.auth.applications.v1beta1.GetAppPasswordResponse');
goog.require('proto.cs3.auth.applications.v1beta1.InvalidateAppPasswordRequest');
goog.require('proto.cs3.auth.applications.v1beta1.InvalidateAppPasswordResponse');
goog.require('proto.cs3.auth.applications.v1beta1.ListAppPasswordsRequest');
goog.require('proto.cs3.auth.applications.v1beta1.ListAppPasswordsResponse');

goog.requireType('grpc.web.ClientOptions');



goog.scope(function() {

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.cs3.auth.applications.v1beta1.ApplicationsAPIClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.cs3.auth.applications.v1beta1.ApplicationsAPIPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.auth.applications.v1beta1.GenerateAppPasswordRequest,
 *   !proto.cs3.auth.applications.v1beta1.GenerateAppPasswordResponse>}
 */
const methodDescriptor_ApplicationsAPI_GenerateAppPassword = new grpc.web.MethodDescriptor(
  '/cs3.auth.applications.v1beta1.ApplicationsAPI/GenerateAppPassword',
  grpc.web.MethodType.UNARY,
  proto.cs3.auth.applications.v1beta1.GenerateAppPasswordRequest,
  proto.cs3.auth.applications.v1beta1.GenerateAppPasswordResponse,
  /**
   * @param {!proto.cs3.auth.applications.v1beta1.GenerateAppPasswordRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.auth.applications.v1beta1.GenerateAppPasswordResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.auth.applications.v1beta1.GenerateAppPasswordRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cs3.auth.applications.v1beta1.GenerateAppPasswordResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.auth.applications.v1beta1.GenerateAppPasswordResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cs3.auth.applications.v1beta1.ApplicationsAPIClient.prototype.generateAppPassword =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cs3.auth.applications.v1beta1.ApplicationsAPI/GenerateAppPassword',
      request,
      metadata || {},
      methodDescriptor_ApplicationsAPI_GenerateAppPassword,
      callback);
};


/**
 * @param {!proto.cs3.auth.applications.v1beta1.GenerateAppPasswordRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cs3.auth.applications.v1beta1.GenerateAppPasswordResponse>}
 *     Promise that resolves to the response
 */
proto.cs3.auth.applications.v1beta1.ApplicationsAPIPromiseClient.prototype.generateAppPassword =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cs3.auth.applications.v1beta1.ApplicationsAPI/GenerateAppPassword',
      request,
      metadata || {},
      methodDescriptor_ApplicationsAPI_GenerateAppPassword);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.auth.applications.v1beta1.ListAppPasswordsRequest,
 *   !proto.cs3.auth.applications.v1beta1.ListAppPasswordsResponse>}
 */
const methodDescriptor_ApplicationsAPI_ListAppPasswords = new grpc.web.MethodDescriptor(
  '/cs3.auth.applications.v1beta1.ApplicationsAPI/ListAppPasswords',
  grpc.web.MethodType.UNARY,
  proto.cs3.auth.applications.v1beta1.ListAppPasswordsRequest,
  proto.cs3.auth.applications.v1beta1.ListAppPasswordsResponse,
  /**
   * @param {!proto.cs3.auth.applications.v1beta1.ListAppPasswordsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.auth.applications.v1beta1.ListAppPasswordsResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.auth.applications.v1beta1.ListAppPasswordsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cs3.auth.applications.v1beta1.ListAppPasswordsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.auth.applications.v1beta1.ListAppPasswordsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cs3.auth.applications.v1beta1.ApplicationsAPIClient.prototype.listAppPasswords =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cs3.auth.applications.v1beta1.ApplicationsAPI/ListAppPasswords',
      request,
      metadata || {},
      methodDescriptor_ApplicationsAPI_ListAppPasswords,
      callback);
};


/**
 * @param {!proto.cs3.auth.applications.v1beta1.ListAppPasswordsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cs3.auth.applications.v1beta1.ListAppPasswordsResponse>}
 *     Promise that resolves to the response
 */
proto.cs3.auth.applications.v1beta1.ApplicationsAPIPromiseClient.prototype.listAppPasswords =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cs3.auth.applications.v1beta1.ApplicationsAPI/ListAppPasswords',
      request,
      metadata || {},
      methodDescriptor_ApplicationsAPI_ListAppPasswords);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.auth.applications.v1beta1.InvalidateAppPasswordRequest,
 *   !proto.cs3.auth.applications.v1beta1.InvalidateAppPasswordResponse>}
 */
const methodDescriptor_ApplicationsAPI_InvalidateAppPassword = new grpc.web.MethodDescriptor(
  '/cs3.auth.applications.v1beta1.ApplicationsAPI/InvalidateAppPassword',
  grpc.web.MethodType.UNARY,
  proto.cs3.auth.applications.v1beta1.InvalidateAppPasswordRequest,
  proto.cs3.auth.applications.v1beta1.InvalidateAppPasswordResponse,
  /**
   * @param {!proto.cs3.auth.applications.v1beta1.InvalidateAppPasswordRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.auth.applications.v1beta1.InvalidateAppPasswordResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.auth.applications.v1beta1.InvalidateAppPasswordRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cs3.auth.applications.v1beta1.InvalidateAppPasswordResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.auth.applications.v1beta1.InvalidateAppPasswordResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cs3.auth.applications.v1beta1.ApplicationsAPIClient.prototype.invalidateAppPassword =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cs3.auth.applications.v1beta1.ApplicationsAPI/InvalidateAppPassword',
      request,
      metadata || {},
      methodDescriptor_ApplicationsAPI_InvalidateAppPassword,
      callback);
};


/**
 * @param {!proto.cs3.auth.applications.v1beta1.InvalidateAppPasswordRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cs3.auth.applications.v1beta1.InvalidateAppPasswordResponse>}
 *     Promise that resolves to the response
 */
proto.cs3.auth.applications.v1beta1.ApplicationsAPIPromiseClient.prototype.invalidateAppPassword =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cs3.auth.applications.v1beta1.ApplicationsAPI/InvalidateAppPassword',
      request,
      metadata || {},
      methodDescriptor_ApplicationsAPI_InvalidateAppPassword);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.auth.applications.v1beta1.GetAppPasswordRequest,
 *   !proto.cs3.auth.applications.v1beta1.GetAppPasswordResponse>}
 */
const methodDescriptor_ApplicationsAPI_GetAppPassword = new grpc.web.MethodDescriptor(
  '/cs3.auth.applications.v1beta1.ApplicationsAPI/GetAppPassword',
  grpc.web.MethodType.UNARY,
  proto.cs3.auth.applications.v1beta1.GetAppPasswordRequest,
  proto.cs3.auth.applications.v1beta1.GetAppPasswordResponse,
  /**
   * @param {!proto.cs3.auth.applications.v1beta1.GetAppPasswordRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.auth.applications.v1beta1.GetAppPasswordResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.auth.applications.v1beta1.GetAppPasswordRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cs3.auth.applications.v1beta1.GetAppPasswordResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.auth.applications.v1beta1.GetAppPasswordResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cs3.auth.applications.v1beta1.ApplicationsAPIClient.prototype.getAppPassword =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cs3.auth.applications.v1beta1.ApplicationsAPI/GetAppPassword',
      request,
      metadata || {},
      methodDescriptor_ApplicationsAPI_GetAppPassword,
      callback);
};


/**
 * @param {!proto.cs3.auth.applications.v1beta1.GetAppPasswordRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cs3.auth.applications.v1beta1.GetAppPasswordResponse>}
 *     Promise that resolves to the response
 */
proto.cs3.auth.applications.v1beta1.ApplicationsAPIPromiseClient.prototype.getAppPassword =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cs3.auth.applications.v1beta1.ApplicationsAPI/GetAppPassword',
      request,
      metadata || {},
      methodDescriptor_ApplicationsAPI_GetAppPassword);
};


}); // goog.scope

