/**
 * @fileoverview gRPC-Web generated client stub for cs3.storage.provider.v1beta1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v0.0.0
// source: cs3/storage/provider/v1beta1/provider_api.proto


/* eslint-disable */
// @ts-nocheck


goog.provide('proto.cs3.storage.provider.v1beta1.ProviderAPIClient');
goog.provide('proto.cs3.storage.provider.v1beta1.ProviderAPIPromiseClient');

goog.require('grpc.web.MethodDescriptor');
goog.require('grpc.web.MethodType');
goog.require('grpc.web.GrpcWebClientBase');
goog.require('grpc.web.AbstractClientBase');
goog.require('grpc.web.ClientReadableStream');
goog.require('grpc.web.RpcError');
goog.require('proto.cs3.storage.provider.v1beta1.AddGrantRequest');
goog.require('proto.cs3.storage.provider.v1beta1.AddGrantResponse');
goog.require('proto.cs3.storage.provider.v1beta1.CreateContainerRequest');
goog.require('proto.cs3.storage.provider.v1beta1.CreateContainerResponse');
goog.require('proto.cs3.storage.provider.v1beta1.CreateHomeRequest');
goog.require('proto.cs3.storage.provider.v1beta1.CreateHomeResponse');
goog.require('proto.cs3.storage.provider.v1beta1.CreateReferenceRequest');
goog.require('proto.cs3.storage.provider.v1beta1.CreateReferenceResponse');
goog.require('proto.cs3.storage.provider.v1beta1.CreateSymlinkRequest');
goog.require('proto.cs3.storage.provider.v1beta1.CreateSymlinkResponse');
goog.require('proto.cs3.storage.provider.v1beta1.DeleteRequest');
goog.require('proto.cs3.storage.provider.v1beta1.DeleteResponse');
goog.require('proto.cs3.storage.provider.v1beta1.DenyGrantRequest');
goog.require('proto.cs3.storage.provider.v1beta1.DenyGrantResponse');
goog.require('proto.cs3.storage.provider.v1beta1.GetHomeRequest');
goog.require('proto.cs3.storage.provider.v1beta1.GetHomeResponse');
goog.require('proto.cs3.storage.provider.v1beta1.GetLockRequest');
goog.require('proto.cs3.storage.provider.v1beta1.GetLockResponse');
goog.require('proto.cs3.storage.provider.v1beta1.GetPathRequest');
goog.require('proto.cs3.storage.provider.v1beta1.GetPathResponse');
goog.require('proto.cs3.storage.provider.v1beta1.GetQuotaRequest');
goog.require('proto.cs3.storage.provider.v1beta1.GetQuotaResponse');
goog.require('proto.cs3.storage.provider.v1beta1.InitiateFileDownloadRequest');
goog.require('proto.cs3.storage.provider.v1beta1.InitiateFileDownloadResponse');
goog.require('proto.cs3.storage.provider.v1beta1.InitiateFileUploadRequest');
goog.require('proto.cs3.storage.provider.v1beta1.InitiateFileUploadResponse');
goog.require('proto.cs3.storage.provider.v1beta1.ListContainerRequest');
goog.require('proto.cs3.storage.provider.v1beta1.ListContainerResponse');
goog.require('proto.cs3.storage.provider.v1beta1.ListContainerStreamRequest');
goog.require('proto.cs3.storage.provider.v1beta1.ListContainerStreamResponse');
goog.require('proto.cs3.storage.provider.v1beta1.ListFileVersionsRequest');
goog.require('proto.cs3.storage.provider.v1beta1.ListFileVersionsResponse');
goog.require('proto.cs3.storage.provider.v1beta1.ListGrantsRequest');
goog.require('proto.cs3.storage.provider.v1beta1.ListGrantsResponse');
goog.require('proto.cs3.storage.provider.v1beta1.ListRecycleRequest');
goog.require('proto.cs3.storage.provider.v1beta1.ListRecycleResponse');
goog.require('proto.cs3.storage.provider.v1beta1.ListRecycleStreamRequest');
goog.require('proto.cs3.storage.provider.v1beta1.ListRecycleStreamResponse');
goog.require('proto.cs3.storage.provider.v1beta1.MoveRequest');
goog.require('proto.cs3.storage.provider.v1beta1.MoveResponse');
goog.require('proto.cs3.storage.provider.v1beta1.PurgeRecycleRequest');
goog.require('proto.cs3.storage.provider.v1beta1.PurgeRecycleResponse');
goog.require('proto.cs3.storage.provider.v1beta1.RefreshLockRequest');
goog.require('proto.cs3.storage.provider.v1beta1.RefreshLockResponse');
goog.require('proto.cs3.storage.provider.v1beta1.RemoveGrantRequest');
goog.require('proto.cs3.storage.provider.v1beta1.RemoveGrantResponse');
goog.require('proto.cs3.storage.provider.v1beta1.RestoreFileVersionRequest');
goog.require('proto.cs3.storage.provider.v1beta1.RestoreFileVersionResponse');
goog.require('proto.cs3.storage.provider.v1beta1.RestoreRecycleItemRequest');
goog.require('proto.cs3.storage.provider.v1beta1.RestoreRecycleItemResponse');
goog.require('proto.cs3.storage.provider.v1beta1.SetArbitraryMetadataRequest');
goog.require('proto.cs3.storage.provider.v1beta1.SetArbitraryMetadataResponse');
goog.require('proto.cs3.storage.provider.v1beta1.SetLockRequest');
goog.require('proto.cs3.storage.provider.v1beta1.SetLockResponse');
goog.require('proto.cs3.storage.provider.v1beta1.StatRequest');
goog.require('proto.cs3.storage.provider.v1beta1.StatResponse');
goog.require('proto.cs3.storage.provider.v1beta1.TouchFileRequest');
goog.require('proto.cs3.storage.provider.v1beta1.TouchFileResponse');
goog.require('proto.cs3.storage.provider.v1beta1.UnlockRequest');
goog.require('proto.cs3.storage.provider.v1beta1.UnlockResponse');
goog.require('proto.cs3.storage.provider.v1beta1.UnsetArbitraryMetadataRequest');
goog.require('proto.cs3.storage.provider.v1beta1.UnsetArbitraryMetadataResponse');
goog.require('proto.cs3.storage.provider.v1beta1.UpdateGrantRequest');
goog.require('proto.cs3.storage.provider.v1beta1.UpdateGrantResponse');

goog.requireType('grpc.web.ClientOptions');



goog.scope(function() {

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.storage.provider.v1beta1.AddGrantRequest,
 *   !proto.cs3.storage.provider.v1beta1.AddGrantResponse>}
 */
const methodDescriptor_ProviderAPI_AddGrant = new grpc.web.MethodDescriptor(
  '/cs3.storage.provider.v1beta1.ProviderAPI/AddGrant',
  grpc.web.MethodType.UNARY,
  proto.cs3.storage.provider.v1beta1.AddGrantRequest,
  proto.cs3.storage.provider.v1beta1.AddGrantResponse,
  /**
   * @param {!proto.cs3.storage.provider.v1beta1.AddGrantRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.storage.provider.v1beta1.AddGrantResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.storage.provider.v1beta1.AddGrantRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cs3.storage.provider.v1beta1.AddGrantResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.storage.provider.v1beta1.AddGrantResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIClient.prototype.addGrant =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/AddGrant',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_AddGrant,
      callback);
};


/**
 * @param {!proto.cs3.storage.provider.v1beta1.AddGrantRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cs3.storage.provider.v1beta1.AddGrantResponse>}
 *     Promise that resolves to the response
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIPromiseClient.prototype.addGrant =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/AddGrant',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_AddGrant);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.storage.provider.v1beta1.CreateContainerRequest,
 *   !proto.cs3.storage.provider.v1beta1.CreateContainerResponse>}
 */
const methodDescriptor_ProviderAPI_CreateContainer = new grpc.web.MethodDescriptor(
  '/cs3.storage.provider.v1beta1.ProviderAPI/CreateContainer',
  grpc.web.MethodType.UNARY,
  proto.cs3.storage.provider.v1beta1.CreateContainerRequest,
  proto.cs3.storage.provider.v1beta1.CreateContainerResponse,
  /**
   * @param {!proto.cs3.storage.provider.v1beta1.CreateContainerRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.storage.provider.v1beta1.CreateContainerResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.storage.provider.v1beta1.CreateContainerRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cs3.storage.provider.v1beta1.CreateContainerResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.storage.provider.v1beta1.CreateContainerResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIClient.prototype.createContainer =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/CreateContainer',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_CreateContainer,
      callback);
};


/**
 * @param {!proto.cs3.storage.provider.v1beta1.CreateContainerRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cs3.storage.provider.v1beta1.CreateContainerResponse>}
 *     Promise that resolves to the response
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIPromiseClient.prototype.createContainer =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/CreateContainer',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_CreateContainer);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.storage.provider.v1beta1.TouchFileRequest,
 *   !proto.cs3.storage.provider.v1beta1.TouchFileResponse>}
 */
const methodDescriptor_ProviderAPI_TouchFile = new grpc.web.MethodDescriptor(
  '/cs3.storage.provider.v1beta1.ProviderAPI/TouchFile',
  grpc.web.MethodType.UNARY,
  proto.cs3.storage.provider.v1beta1.TouchFileRequest,
  proto.cs3.storage.provider.v1beta1.TouchFileResponse,
  /**
   * @param {!proto.cs3.storage.provider.v1beta1.TouchFileRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.storage.provider.v1beta1.TouchFileResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.storage.provider.v1beta1.TouchFileRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cs3.storage.provider.v1beta1.TouchFileResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.storage.provider.v1beta1.TouchFileResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIClient.prototype.touchFile =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/TouchFile',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_TouchFile,
      callback);
};


/**
 * @param {!proto.cs3.storage.provider.v1beta1.TouchFileRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cs3.storage.provider.v1beta1.TouchFileResponse>}
 *     Promise that resolves to the response
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIPromiseClient.prototype.touchFile =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/TouchFile',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_TouchFile);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.storage.provider.v1beta1.DeleteRequest,
 *   !proto.cs3.storage.provider.v1beta1.DeleteResponse>}
 */
const methodDescriptor_ProviderAPI_Delete = new grpc.web.MethodDescriptor(
  '/cs3.storage.provider.v1beta1.ProviderAPI/Delete',
  grpc.web.MethodType.UNARY,
  proto.cs3.storage.provider.v1beta1.DeleteRequest,
  proto.cs3.storage.provider.v1beta1.DeleteResponse,
  /**
   * @param {!proto.cs3.storage.provider.v1beta1.DeleteRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.storage.provider.v1beta1.DeleteResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.storage.provider.v1beta1.DeleteRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cs3.storage.provider.v1beta1.DeleteResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.storage.provider.v1beta1.DeleteResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIClient.prototype.delete =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/Delete',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_Delete,
      callback);
};


/**
 * @param {!proto.cs3.storage.provider.v1beta1.DeleteRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cs3.storage.provider.v1beta1.DeleteResponse>}
 *     Promise that resolves to the response
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIPromiseClient.prototype.delete =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/Delete',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_Delete);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.storage.provider.v1beta1.DenyGrantRequest,
 *   !proto.cs3.storage.provider.v1beta1.DenyGrantResponse>}
 */
const methodDescriptor_ProviderAPI_DenyGrant = new grpc.web.MethodDescriptor(
  '/cs3.storage.provider.v1beta1.ProviderAPI/DenyGrant',
  grpc.web.MethodType.UNARY,
  proto.cs3.storage.provider.v1beta1.DenyGrantRequest,
  proto.cs3.storage.provider.v1beta1.DenyGrantResponse,
  /**
   * @param {!proto.cs3.storage.provider.v1beta1.DenyGrantRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.storage.provider.v1beta1.DenyGrantResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.storage.provider.v1beta1.DenyGrantRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cs3.storage.provider.v1beta1.DenyGrantResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.storage.provider.v1beta1.DenyGrantResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIClient.prototype.denyGrant =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/DenyGrant',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_DenyGrant,
      callback);
};


/**
 * @param {!proto.cs3.storage.provider.v1beta1.DenyGrantRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cs3.storage.provider.v1beta1.DenyGrantResponse>}
 *     Promise that resolves to the response
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIPromiseClient.prototype.denyGrant =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/DenyGrant',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_DenyGrant);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.storage.provider.v1beta1.GetPathRequest,
 *   !proto.cs3.storage.provider.v1beta1.GetPathResponse>}
 */
const methodDescriptor_ProviderAPI_GetPath = new grpc.web.MethodDescriptor(
  '/cs3.storage.provider.v1beta1.ProviderAPI/GetPath',
  grpc.web.MethodType.UNARY,
  proto.cs3.storage.provider.v1beta1.GetPathRequest,
  proto.cs3.storage.provider.v1beta1.GetPathResponse,
  /**
   * @param {!proto.cs3.storage.provider.v1beta1.GetPathRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.storage.provider.v1beta1.GetPathResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.storage.provider.v1beta1.GetPathRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cs3.storage.provider.v1beta1.GetPathResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.storage.provider.v1beta1.GetPathResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIClient.prototype.getPath =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/GetPath',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_GetPath,
      callback);
};


/**
 * @param {!proto.cs3.storage.provider.v1beta1.GetPathRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cs3.storage.provider.v1beta1.GetPathResponse>}
 *     Promise that resolves to the response
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIPromiseClient.prototype.getPath =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/GetPath',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_GetPath);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.storage.provider.v1beta1.GetQuotaRequest,
 *   !proto.cs3.storage.provider.v1beta1.GetQuotaResponse>}
 */
const methodDescriptor_ProviderAPI_GetQuota = new grpc.web.MethodDescriptor(
  '/cs3.storage.provider.v1beta1.ProviderAPI/GetQuota',
  grpc.web.MethodType.UNARY,
  proto.cs3.storage.provider.v1beta1.GetQuotaRequest,
  proto.cs3.storage.provider.v1beta1.GetQuotaResponse,
  /**
   * @param {!proto.cs3.storage.provider.v1beta1.GetQuotaRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.storage.provider.v1beta1.GetQuotaResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.storage.provider.v1beta1.GetQuotaRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cs3.storage.provider.v1beta1.GetQuotaResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.storage.provider.v1beta1.GetQuotaResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIClient.prototype.getQuota =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/GetQuota',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_GetQuota,
      callback);
};


/**
 * @param {!proto.cs3.storage.provider.v1beta1.GetQuotaRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cs3.storage.provider.v1beta1.GetQuotaResponse>}
 *     Promise that resolves to the response
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIPromiseClient.prototype.getQuota =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/GetQuota',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_GetQuota);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.storage.provider.v1beta1.InitiateFileDownloadRequest,
 *   !proto.cs3.storage.provider.v1beta1.InitiateFileDownloadResponse>}
 */
const methodDescriptor_ProviderAPI_InitiateFileDownload = new grpc.web.MethodDescriptor(
  '/cs3.storage.provider.v1beta1.ProviderAPI/InitiateFileDownload',
  grpc.web.MethodType.UNARY,
  proto.cs3.storage.provider.v1beta1.InitiateFileDownloadRequest,
  proto.cs3.storage.provider.v1beta1.InitiateFileDownloadResponse,
  /**
   * @param {!proto.cs3.storage.provider.v1beta1.InitiateFileDownloadRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.storage.provider.v1beta1.InitiateFileDownloadResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.storage.provider.v1beta1.InitiateFileDownloadRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cs3.storage.provider.v1beta1.InitiateFileDownloadResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.storage.provider.v1beta1.InitiateFileDownloadResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIClient.prototype.initiateFileDownload =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/InitiateFileDownload',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_InitiateFileDownload,
      callback);
};


/**
 * @param {!proto.cs3.storage.provider.v1beta1.InitiateFileDownloadRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cs3.storage.provider.v1beta1.InitiateFileDownloadResponse>}
 *     Promise that resolves to the response
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIPromiseClient.prototype.initiateFileDownload =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/InitiateFileDownload',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_InitiateFileDownload);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.storage.provider.v1beta1.InitiateFileUploadRequest,
 *   !proto.cs3.storage.provider.v1beta1.InitiateFileUploadResponse>}
 */
const methodDescriptor_ProviderAPI_InitiateFileUpload = new grpc.web.MethodDescriptor(
  '/cs3.storage.provider.v1beta1.ProviderAPI/InitiateFileUpload',
  grpc.web.MethodType.UNARY,
  proto.cs3.storage.provider.v1beta1.InitiateFileUploadRequest,
  proto.cs3.storage.provider.v1beta1.InitiateFileUploadResponse,
  /**
   * @param {!proto.cs3.storage.provider.v1beta1.InitiateFileUploadRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.storage.provider.v1beta1.InitiateFileUploadResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.storage.provider.v1beta1.InitiateFileUploadRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cs3.storage.provider.v1beta1.InitiateFileUploadResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.storage.provider.v1beta1.InitiateFileUploadResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIClient.prototype.initiateFileUpload =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/InitiateFileUpload',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_InitiateFileUpload,
      callback);
};


/**
 * @param {!proto.cs3.storage.provider.v1beta1.InitiateFileUploadRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cs3.storage.provider.v1beta1.InitiateFileUploadResponse>}
 *     Promise that resolves to the response
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIPromiseClient.prototype.initiateFileUpload =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/InitiateFileUpload',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_InitiateFileUpload);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.storage.provider.v1beta1.ListGrantsRequest,
 *   !proto.cs3.storage.provider.v1beta1.ListGrantsResponse>}
 */
const methodDescriptor_ProviderAPI_ListGrants = new grpc.web.MethodDescriptor(
  '/cs3.storage.provider.v1beta1.ProviderAPI/ListGrants',
  grpc.web.MethodType.UNARY,
  proto.cs3.storage.provider.v1beta1.ListGrantsRequest,
  proto.cs3.storage.provider.v1beta1.ListGrantsResponse,
  /**
   * @param {!proto.cs3.storage.provider.v1beta1.ListGrantsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.storage.provider.v1beta1.ListGrantsResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.storage.provider.v1beta1.ListGrantsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cs3.storage.provider.v1beta1.ListGrantsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.storage.provider.v1beta1.ListGrantsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIClient.prototype.listGrants =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/ListGrants',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_ListGrants,
      callback);
};


/**
 * @param {!proto.cs3.storage.provider.v1beta1.ListGrantsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cs3.storage.provider.v1beta1.ListGrantsResponse>}
 *     Promise that resolves to the response
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIPromiseClient.prototype.listGrants =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/ListGrants',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_ListGrants);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.storage.provider.v1beta1.ListContainerStreamRequest,
 *   !proto.cs3.storage.provider.v1beta1.ListContainerStreamResponse>}
 */
const methodDescriptor_ProviderAPI_ListContainerStream = new grpc.web.MethodDescriptor(
  '/cs3.storage.provider.v1beta1.ProviderAPI/ListContainerStream',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.cs3.storage.provider.v1beta1.ListContainerStreamRequest,
  proto.cs3.storage.provider.v1beta1.ListContainerStreamResponse,
  /**
   * @param {!proto.cs3.storage.provider.v1beta1.ListContainerStreamRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.storage.provider.v1beta1.ListContainerStreamResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.storage.provider.v1beta1.ListContainerStreamRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.storage.provider.v1beta1.ListContainerStreamResponse>}
 *     The XHR Node Readable Stream
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIClient.prototype.listContainerStream =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/ListContainerStream',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_ListContainerStream);
};


/**
 * @param {!proto.cs3.storage.provider.v1beta1.ListContainerStreamRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.storage.provider.v1beta1.ListContainerStreamResponse>}
 *     The XHR Node Readable Stream
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIPromiseClient.prototype.listContainerStream =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/ListContainerStream',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_ListContainerStream);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.storage.provider.v1beta1.ListContainerRequest,
 *   !proto.cs3.storage.provider.v1beta1.ListContainerResponse>}
 */
const methodDescriptor_ProviderAPI_ListContainer = new grpc.web.MethodDescriptor(
  '/cs3.storage.provider.v1beta1.ProviderAPI/ListContainer',
  grpc.web.MethodType.UNARY,
  proto.cs3.storage.provider.v1beta1.ListContainerRequest,
  proto.cs3.storage.provider.v1beta1.ListContainerResponse,
  /**
   * @param {!proto.cs3.storage.provider.v1beta1.ListContainerRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.storage.provider.v1beta1.ListContainerResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.storage.provider.v1beta1.ListContainerRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cs3.storage.provider.v1beta1.ListContainerResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.storage.provider.v1beta1.ListContainerResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIClient.prototype.listContainer =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/ListContainer',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_ListContainer,
      callback);
};


/**
 * @param {!proto.cs3.storage.provider.v1beta1.ListContainerRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cs3.storage.provider.v1beta1.ListContainerResponse>}
 *     Promise that resolves to the response
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIPromiseClient.prototype.listContainer =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/ListContainer',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_ListContainer);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.storage.provider.v1beta1.ListFileVersionsRequest,
 *   !proto.cs3.storage.provider.v1beta1.ListFileVersionsResponse>}
 */
const methodDescriptor_ProviderAPI_ListFileVersions = new grpc.web.MethodDescriptor(
  '/cs3.storage.provider.v1beta1.ProviderAPI/ListFileVersions',
  grpc.web.MethodType.UNARY,
  proto.cs3.storage.provider.v1beta1.ListFileVersionsRequest,
  proto.cs3.storage.provider.v1beta1.ListFileVersionsResponse,
  /**
   * @param {!proto.cs3.storage.provider.v1beta1.ListFileVersionsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.storage.provider.v1beta1.ListFileVersionsResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.storage.provider.v1beta1.ListFileVersionsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cs3.storage.provider.v1beta1.ListFileVersionsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.storage.provider.v1beta1.ListFileVersionsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIClient.prototype.listFileVersions =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/ListFileVersions',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_ListFileVersions,
      callback);
};


/**
 * @param {!proto.cs3.storage.provider.v1beta1.ListFileVersionsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cs3.storage.provider.v1beta1.ListFileVersionsResponse>}
 *     Promise that resolves to the response
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIPromiseClient.prototype.listFileVersions =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/ListFileVersions',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_ListFileVersions);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.storage.provider.v1beta1.ListRecycleStreamRequest,
 *   !proto.cs3.storage.provider.v1beta1.ListRecycleStreamResponse>}
 */
const methodDescriptor_ProviderAPI_ListRecycleStream = new grpc.web.MethodDescriptor(
  '/cs3.storage.provider.v1beta1.ProviderAPI/ListRecycleStream',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.cs3.storage.provider.v1beta1.ListRecycleStreamRequest,
  proto.cs3.storage.provider.v1beta1.ListRecycleStreamResponse,
  /**
   * @param {!proto.cs3.storage.provider.v1beta1.ListRecycleStreamRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.storage.provider.v1beta1.ListRecycleStreamResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.storage.provider.v1beta1.ListRecycleStreamRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.storage.provider.v1beta1.ListRecycleStreamResponse>}
 *     The XHR Node Readable Stream
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIClient.prototype.listRecycleStream =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/ListRecycleStream',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_ListRecycleStream);
};


/**
 * @param {!proto.cs3.storage.provider.v1beta1.ListRecycleStreamRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.storage.provider.v1beta1.ListRecycleStreamResponse>}
 *     The XHR Node Readable Stream
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIPromiseClient.prototype.listRecycleStream =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/ListRecycleStream',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_ListRecycleStream);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.storage.provider.v1beta1.ListRecycleRequest,
 *   !proto.cs3.storage.provider.v1beta1.ListRecycleResponse>}
 */
const methodDescriptor_ProviderAPI_ListRecycle = new grpc.web.MethodDescriptor(
  '/cs3.storage.provider.v1beta1.ProviderAPI/ListRecycle',
  grpc.web.MethodType.UNARY,
  proto.cs3.storage.provider.v1beta1.ListRecycleRequest,
  proto.cs3.storage.provider.v1beta1.ListRecycleResponse,
  /**
   * @param {!proto.cs3.storage.provider.v1beta1.ListRecycleRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.storage.provider.v1beta1.ListRecycleResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.storage.provider.v1beta1.ListRecycleRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cs3.storage.provider.v1beta1.ListRecycleResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.storage.provider.v1beta1.ListRecycleResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIClient.prototype.listRecycle =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/ListRecycle',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_ListRecycle,
      callback);
};


/**
 * @param {!proto.cs3.storage.provider.v1beta1.ListRecycleRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cs3.storage.provider.v1beta1.ListRecycleResponse>}
 *     Promise that resolves to the response
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIPromiseClient.prototype.listRecycle =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/ListRecycle',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_ListRecycle);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.storage.provider.v1beta1.MoveRequest,
 *   !proto.cs3.storage.provider.v1beta1.MoveResponse>}
 */
const methodDescriptor_ProviderAPI_Move = new grpc.web.MethodDescriptor(
  '/cs3.storage.provider.v1beta1.ProviderAPI/Move',
  grpc.web.MethodType.UNARY,
  proto.cs3.storage.provider.v1beta1.MoveRequest,
  proto.cs3.storage.provider.v1beta1.MoveResponse,
  /**
   * @param {!proto.cs3.storage.provider.v1beta1.MoveRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.storage.provider.v1beta1.MoveResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.storage.provider.v1beta1.MoveRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cs3.storage.provider.v1beta1.MoveResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.storage.provider.v1beta1.MoveResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIClient.prototype.move =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/Move',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_Move,
      callback);
};


/**
 * @param {!proto.cs3.storage.provider.v1beta1.MoveRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cs3.storage.provider.v1beta1.MoveResponse>}
 *     Promise that resolves to the response
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIPromiseClient.prototype.move =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/Move',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_Move);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.storage.provider.v1beta1.RemoveGrantRequest,
 *   !proto.cs3.storage.provider.v1beta1.RemoveGrantResponse>}
 */
const methodDescriptor_ProviderAPI_RemoveGrant = new grpc.web.MethodDescriptor(
  '/cs3.storage.provider.v1beta1.ProviderAPI/RemoveGrant',
  grpc.web.MethodType.UNARY,
  proto.cs3.storage.provider.v1beta1.RemoveGrantRequest,
  proto.cs3.storage.provider.v1beta1.RemoveGrantResponse,
  /**
   * @param {!proto.cs3.storage.provider.v1beta1.RemoveGrantRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.storage.provider.v1beta1.RemoveGrantResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.storage.provider.v1beta1.RemoveGrantRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cs3.storage.provider.v1beta1.RemoveGrantResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.storage.provider.v1beta1.RemoveGrantResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIClient.prototype.removeGrant =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/RemoveGrant',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_RemoveGrant,
      callback);
};


/**
 * @param {!proto.cs3.storage.provider.v1beta1.RemoveGrantRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cs3.storage.provider.v1beta1.RemoveGrantResponse>}
 *     Promise that resolves to the response
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIPromiseClient.prototype.removeGrant =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/RemoveGrant',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_RemoveGrant);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.storage.provider.v1beta1.PurgeRecycleRequest,
 *   !proto.cs3.storage.provider.v1beta1.PurgeRecycleResponse>}
 */
const methodDescriptor_ProviderAPI_PurgeRecycle = new grpc.web.MethodDescriptor(
  '/cs3.storage.provider.v1beta1.ProviderAPI/PurgeRecycle',
  grpc.web.MethodType.UNARY,
  proto.cs3.storage.provider.v1beta1.PurgeRecycleRequest,
  proto.cs3.storage.provider.v1beta1.PurgeRecycleResponse,
  /**
   * @param {!proto.cs3.storage.provider.v1beta1.PurgeRecycleRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.storage.provider.v1beta1.PurgeRecycleResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.storage.provider.v1beta1.PurgeRecycleRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cs3.storage.provider.v1beta1.PurgeRecycleResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.storage.provider.v1beta1.PurgeRecycleResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIClient.prototype.purgeRecycle =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/PurgeRecycle',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_PurgeRecycle,
      callback);
};


/**
 * @param {!proto.cs3.storage.provider.v1beta1.PurgeRecycleRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cs3.storage.provider.v1beta1.PurgeRecycleResponse>}
 *     Promise that resolves to the response
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIPromiseClient.prototype.purgeRecycle =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/PurgeRecycle',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_PurgeRecycle);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.storage.provider.v1beta1.RestoreFileVersionRequest,
 *   !proto.cs3.storage.provider.v1beta1.RestoreFileVersionResponse>}
 */
const methodDescriptor_ProviderAPI_RestoreFileVersion = new grpc.web.MethodDescriptor(
  '/cs3.storage.provider.v1beta1.ProviderAPI/RestoreFileVersion',
  grpc.web.MethodType.UNARY,
  proto.cs3.storage.provider.v1beta1.RestoreFileVersionRequest,
  proto.cs3.storage.provider.v1beta1.RestoreFileVersionResponse,
  /**
   * @param {!proto.cs3.storage.provider.v1beta1.RestoreFileVersionRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.storage.provider.v1beta1.RestoreFileVersionResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.storage.provider.v1beta1.RestoreFileVersionRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cs3.storage.provider.v1beta1.RestoreFileVersionResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.storage.provider.v1beta1.RestoreFileVersionResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIClient.prototype.restoreFileVersion =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/RestoreFileVersion',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_RestoreFileVersion,
      callback);
};


/**
 * @param {!proto.cs3.storage.provider.v1beta1.RestoreFileVersionRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cs3.storage.provider.v1beta1.RestoreFileVersionResponse>}
 *     Promise that resolves to the response
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIPromiseClient.prototype.restoreFileVersion =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/RestoreFileVersion',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_RestoreFileVersion);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.storage.provider.v1beta1.RestoreRecycleItemRequest,
 *   !proto.cs3.storage.provider.v1beta1.RestoreRecycleItemResponse>}
 */
const methodDescriptor_ProviderAPI_RestoreRecycleItem = new grpc.web.MethodDescriptor(
  '/cs3.storage.provider.v1beta1.ProviderAPI/RestoreRecycleItem',
  grpc.web.MethodType.UNARY,
  proto.cs3.storage.provider.v1beta1.RestoreRecycleItemRequest,
  proto.cs3.storage.provider.v1beta1.RestoreRecycleItemResponse,
  /**
   * @param {!proto.cs3.storage.provider.v1beta1.RestoreRecycleItemRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.storage.provider.v1beta1.RestoreRecycleItemResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.storage.provider.v1beta1.RestoreRecycleItemRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cs3.storage.provider.v1beta1.RestoreRecycleItemResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.storage.provider.v1beta1.RestoreRecycleItemResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIClient.prototype.restoreRecycleItem =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/RestoreRecycleItem',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_RestoreRecycleItem,
      callback);
};


/**
 * @param {!proto.cs3.storage.provider.v1beta1.RestoreRecycleItemRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cs3.storage.provider.v1beta1.RestoreRecycleItemResponse>}
 *     Promise that resolves to the response
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIPromiseClient.prototype.restoreRecycleItem =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/RestoreRecycleItem',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_RestoreRecycleItem);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.storage.provider.v1beta1.StatRequest,
 *   !proto.cs3.storage.provider.v1beta1.StatResponse>}
 */
const methodDescriptor_ProviderAPI_Stat = new grpc.web.MethodDescriptor(
  '/cs3.storage.provider.v1beta1.ProviderAPI/Stat',
  grpc.web.MethodType.UNARY,
  proto.cs3.storage.provider.v1beta1.StatRequest,
  proto.cs3.storage.provider.v1beta1.StatResponse,
  /**
   * @param {!proto.cs3.storage.provider.v1beta1.StatRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.storage.provider.v1beta1.StatResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.storage.provider.v1beta1.StatRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cs3.storage.provider.v1beta1.StatResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.storage.provider.v1beta1.StatResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIClient.prototype.stat =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/Stat',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_Stat,
      callback);
};


/**
 * @param {!proto.cs3.storage.provider.v1beta1.StatRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cs3.storage.provider.v1beta1.StatResponse>}
 *     Promise that resolves to the response
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIPromiseClient.prototype.stat =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/Stat',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_Stat);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.storage.provider.v1beta1.UpdateGrantRequest,
 *   !proto.cs3.storage.provider.v1beta1.UpdateGrantResponse>}
 */
const methodDescriptor_ProviderAPI_UpdateGrant = new grpc.web.MethodDescriptor(
  '/cs3.storage.provider.v1beta1.ProviderAPI/UpdateGrant',
  grpc.web.MethodType.UNARY,
  proto.cs3.storage.provider.v1beta1.UpdateGrantRequest,
  proto.cs3.storage.provider.v1beta1.UpdateGrantResponse,
  /**
   * @param {!proto.cs3.storage.provider.v1beta1.UpdateGrantRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.storage.provider.v1beta1.UpdateGrantResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.storage.provider.v1beta1.UpdateGrantRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cs3.storage.provider.v1beta1.UpdateGrantResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.storage.provider.v1beta1.UpdateGrantResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIClient.prototype.updateGrant =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/UpdateGrant',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_UpdateGrant,
      callback);
};


/**
 * @param {!proto.cs3.storage.provider.v1beta1.UpdateGrantRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cs3.storage.provider.v1beta1.UpdateGrantResponse>}
 *     Promise that resolves to the response
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIPromiseClient.prototype.updateGrant =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/UpdateGrant',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_UpdateGrant);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.storage.provider.v1beta1.CreateSymlinkRequest,
 *   !proto.cs3.storage.provider.v1beta1.CreateSymlinkResponse>}
 */
const methodDescriptor_ProviderAPI_CreateSymlink = new grpc.web.MethodDescriptor(
  '/cs3.storage.provider.v1beta1.ProviderAPI/CreateSymlink',
  grpc.web.MethodType.UNARY,
  proto.cs3.storage.provider.v1beta1.CreateSymlinkRequest,
  proto.cs3.storage.provider.v1beta1.CreateSymlinkResponse,
  /**
   * @param {!proto.cs3.storage.provider.v1beta1.CreateSymlinkRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.storage.provider.v1beta1.CreateSymlinkResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.storage.provider.v1beta1.CreateSymlinkRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cs3.storage.provider.v1beta1.CreateSymlinkResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.storage.provider.v1beta1.CreateSymlinkResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIClient.prototype.createSymlink =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/CreateSymlink',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_CreateSymlink,
      callback);
};


/**
 * @param {!proto.cs3.storage.provider.v1beta1.CreateSymlinkRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cs3.storage.provider.v1beta1.CreateSymlinkResponse>}
 *     Promise that resolves to the response
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIPromiseClient.prototype.createSymlink =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/CreateSymlink',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_CreateSymlink);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.storage.provider.v1beta1.CreateReferenceRequest,
 *   !proto.cs3.storage.provider.v1beta1.CreateReferenceResponse>}
 */
const methodDescriptor_ProviderAPI_CreateReference = new grpc.web.MethodDescriptor(
  '/cs3.storage.provider.v1beta1.ProviderAPI/CreateReference',
  grpc.web.MethodType.UNARY,
  proto.cs3.storage.provider.v1beta1.CreateReferenceRequest,
  proto.cs3.storage.provider.v1beta1.CreateReferenceResponse,
  /**
   * @param {!proto.cs3.storage.provider.v1beta1.CreateReferenceRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.storage.provider.v1beta1.CreateReferenceResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.storage.provider.v1beta1.CreateReferenceRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cs3.storage.provider.v1beta1.CreateReferenceResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.storage.provider.v1beta1.CreateReferenceResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIClient.prototype.createReference =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/CreateReference',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_CreateReference,
      callback);
};


/**
 * @param {!proto.cs3.storage.provider.v1beta1.CreateReferenceRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cs3.storage.provider.v1beta1.CreateReferenceResponse>}
 *     Promise that resolves to the response
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIPromiseClient.prototype.createReference =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/CreateReference',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_CreateReference);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.storage.provider.v1beta1.SetArbitraryMetadataRequest,
 *   !proto.cs3.storage.provider.v1beta1.SetArbitraryMetadataResponse>}
 */
const methodDescriptor_ProviderAPI_SetArbitraryMetadata = new grpc.web.MethodDescriptor(
  '/cs3.storage.provider.v1beta1.ProviderAPI/SetArbitraryMetadata',
  grpc.web.MethodType.UNARY,
  proto.cs3.storage.provider.v1beta1.SetArbitraryMetadataRequest,
  proto.cs3.storage.provider.v1beta1.SetArbitraryMetadataResponse,
  /**
   * @param {!proto.cs3.storage.provider.v1beta1.SetArbitraryMetadataRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.storage.provider.v1beta1.SetArbitraryMetadataResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.storage.provider.v1beta1.SetArbitraryMetadataRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cs3.storage.provider.v1beta1.SetArbitraryMetadataResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.storage.provider.v1beta1.SetArbitraryMetadataResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIClient.prototype.setArbitraryMetadata =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/SetArbitraryMetadata',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_SetArbitraryMetadata,
      callback);
};


/**
 * @param {!proto.cs3.storage.provider.v1beta1.SetArbitraryMetadataRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cs3.storage.provider.v1beta1.SetArbitraryMetadataResponse>}
 *     Promise that resolves to the response
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIPromiseClient.prototype.setArbitraryMetadata =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/SetArbitraryMetadata',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_SetArbitraryMetadata);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.storage.provider.v1beta1.UnsetArbitraryMetadataRequest,
 *   !proto.cs3.storage.provider.v1beta1.UnsetArbitraryMetadataResponse>}
 */
const methodDescriptor_ProviderAPI_UnsetArbitraryMetadata = new grpc.web.MethodDescriptor(
  '/cs3.storage.provider.v1beta1.ProviderAPI/UnsetArbitraryMetadata',
  grpc.web.MethodType.UNARY,
  proto.cs3.storage.provider.v1beta1.UnsetArbitraryMetadataRequest,
  proto.cs3.storage.provider.v1beta1.UnsetArbitraryMetadataResponse,
  /**
   * @param {!proto.cs3.storage.provider.v1beta1.UnsetArbitraryMetadataRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.storage.provider.v1beta1.UnsetArbitraryMetadataResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.storage.provider.v1beta1.UnsetArbitraryMetadataRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cs3.storage.provider.v1beta1.UnsetArbitraryMetadataResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.storage.provider.v1beta1.UnsetArbitraryMetadataResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIClient.prototype.unsetArbitraryMetadata =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/UnsetArbitraryMetadata',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_UnsetArbitraryMetadata,
      callback);
};


/**
 * @param {!proto.cs3.storage.provider.v1beta1.UnsetArbitraryMetadataRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cs3.storage.provider.v1beta1.UnsetArbitraryMetadataResponse>}
 *     Promise that resolves to the response
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIPromiseClient.prototype.unsetArbitraryMetadata =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/UnsetArbitraryMetadata',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_UnsetArbitraryMetadata);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.storage.provider.v1beta1.SetLockRequest,
 *   !proto.cs3.storage.provider.v1beta1.SetLockResponse>}
 */
const methodDescriptor_ProviderAPI_SetLock = new grpc.web.MethodDescriptor(
  '/cs3.storage.provider.v1beta1.ProviderAPI/SetLock',
  grpc.web.MethodType.UNARY,
  proto.cs3.storage.provider.v1beta1.SetLockRequest,
  proto.cs3.storage.provider.v1beta1.SetLockResponse,
  /**
   * @param {!proto.cs3.storage.provider.v1beta1.SetLockRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.storage.provider.v1beta1.SetLockResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.storage.provider.v1beta1.SetLockRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cs3.storage.provider.v1beta1.SetLockResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.storage.provider.v1beta1.SetLockResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIClient.prototype.setLock =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/SetLock',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_SetLock,
      callback);
};


/**
 * @param {!proto.cs3.storage.provider.v1beta1.SetLockRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cs3.storage.provider.v1beta1.SetLockResponse>}
 *     Promise that resolves to the response
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIPromiseClient.prototype.setLock =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/SetLock',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_SetLock);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.storage.provider.v1beta1.GetLockRequest,
 *   !proto.cs3.storage.provider.v1beta1.GetLockResponse>}
 */
const methodDescriptor_ProviderAPI_GetLock = new grpc.web.MethodDescriptor(
  '/cs3.storage.provider.v1beta1.ProviderAPI/GetLock',
  grpc.web.MethodType.UNARY,
  proto.cs3.storage.provider.v1beta1.GetLockRequest,
  proto.cs3.storage.provider.v1beta1.GetLockResponse,
  /**
   * @param {!proto.cs3.storage.provider.v1beta1.GetLockRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.storage.provider.v1beta1.GetLockResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.storage.provider.v1beta1.GetLockRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cs3.storage.provider.v1beta1.GetLockResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.storage.provider.v1beta1.GetLockResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIClient.prototype.getLock =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/GetLock',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_GetLock,
      callback);
};


/**
 * @param {!proto.cs3.storage.provider.v1beta1.GetLockRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cs3.storage.provider.v1beta1.GetLockResponse>}
 *     Promise that resolves to the response
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIPromiseClient.prototype.getLock =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/GetLock',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_GetLock);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.storage.provider.v1beta1.RefreshLockRequest,
 *   !proto.cs3.storage.provider.v1beta1.RefreshLockResponse>}
 */
const methodDescriptor_ProviderAPI_RefreshLock = new grpc.web.MethodDescriptor(
  '/cs3.storage.provider.v1beta1.ProviderAPI/RefreshLock',
  grpc.web.MethodType.UNARY,
  proto.cs3.storage.provider.v1beta1.RefreshLockRequest,
  proto.cs3.storage.provider.v1beta1.RefreshLockResponse,
  /**
   * @param {!proto.cs3.storage.provider.v1beta1.RefreshLockRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.storage.provider.v1beta1.RefreshLockResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.storage.provider.v1beta1.RefreshLockRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cs3.storage.provider.v1beta1.RefreshLockResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.storage.provider.v1beta1.RefreshLockResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIClient.prototype.refreshLock =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/RefreshLock',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_RefreshLock,
      callback);
};


/**
 * @param {!proto.cs3.storage.provider.v1beta1.RefreshLockRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cs3.storage.provider.v1beta1.RefreshLockResponse>}
 *     Promise that resolves to the response
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIPromiseClient.prototype.refreshLock =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/RefreshLock',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_RefreshLock);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.storage.provider.v1beta1.UnlockRequest,
 *   !proto.cs3.storage.provider.v1beta1.UnlockResponse>}
 */
const methodDescriptor_ProviderAPI_Unlock = new grpc.web.MethodDescriptor(
  '/cs3.storage.provider.v1beta1.ProviderAPI/Unlock',
  grpc.web.MethodType.UNARY,
  proto.cs3.storage.provider.v1beta1.UnlockRequest,
  proto.cs3.storage.provider.v1beta1.UnlockResponse,
  /**
   * @param {!proto.cs3.storage.provider.v1beta1.UnlockRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.storage.provider.v1beta1.UnlockResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.storage.provider.v1beta1.UnlockRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cs3.storage.provider.v1beta1.UnlockResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.storage.provider.v1beta1.UnlockResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIClient.prototype.unlock =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/Unlock',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_Unlock,
      callback);
};


/**
 * @param {!proto.cs3.storage.provider.v1beta1.UnlockRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cs3.storage.provider.v1beta1.UnlockResponse>}
 *     Promise that resolves to the response
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIPromiseClient.prototype.unlock =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/Unlock',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_Unlock);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.storage.provider.v1beta1.CreateHomeRequest,
 *   !proto.cs3.storage.provider.v1beta1.CreateHomeResponse>}
 */
const methodDescriptor_ProviderAPI_CreateHome = new grpc.web.MethodDescriptor(
  '/cs3.storage.provider.v1beta1.ProviderAPI/CreateHome',
  grpc.web.MethodType.UNARY,
  proto.cs3.storage.provider.v1beta1.CreateHomeRequest,
  proto.cs3.storage.provider.v1beta1.CreateHomeResponse,
  /**
   * @param {!proto.cs3.storage.provider.v1beta1.CreateHomeRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.storage.provider.v1beta1.CreateHomeResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.storage.provider.v1beta1.CreateHomeRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cs3.storage.provider.v1beta1.CreateHomeResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.storage.provider.v1beta1.CreateHomeResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIClient.prototype.createHome =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/CreateHome',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_CreateHome,
      callback);
};


/**
 * @param {!proto.cs3.storage.provider.v1beta1.CreateHomeRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cs3.storage.provider.v1beta1.CreateHomeResponse>}
 *     Promise that resolves to the response
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIPromiseClient.prototype.createHome =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/CreateHome',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_CreateHome);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cs3.storage.provider.v1beta1.GetHomeRequest,
 *   !proto.cs3.storage.provider.v1beta1.GetHomeResponse>}
 */
const methodDescriptor_ProviderAPI_GetHome = new grpc.web.MethodDescriptor(
  '/cs3.storage.provider.v1beta1.ProviderAPI/GetHome',
  grpc.web.MethodType.UNARY,
  proto.cs3.storage.provider.v1beta1.GetHomeRequest,
  proto.cs3.storage.provider.v1beta1.GetHomeResponse,
  /**
   * @param {!proto.cs3.storage.provider.v1beta1.GetHomeRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cs3.storage.provider.v1beta1.GetHomeResponse.deserializeBinary
);


/**
 * @param {!proto.cs3.storage.provider.v1beta1.GetHomeRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cs3.storage.provider.v1beta1.GetHomeResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cs3.storage.provider.v1beta1.GetHomeResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIClient.prototype.getHome =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/GetHome',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_GetHome,
      callback);
};


/**
 * @param {!proto.cs3.storage.provider.v1beta1.GetHomeRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cs3.storage.provider.v1beta1.GetHomeResponse>}
 *     Promise that resolves to the response
 */
proto.cs3.storage.provider.v1beta1.ProviderAPIPromiseClient.prototype.getHome =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cs3.storage.provider.v1beta1.ProviderAPI/GetHome',
      request,
      metadata || {},
      methodDescriptor_ProviderAPI_GetHome);
};


}); // goog.scope

